/**
 * Regenerates the Logto client from `spec/openapi.json`.
 *
 *   bun run generate                                    # from the pinned spec
 *   bun run generate --fetch https://auth.example.com   # refresh the spec first
 *
 * Pipeline: normalise the spec -> run `@effect/openapi-generator` once -> parse its single
 * output file -> split it per OpenAPI tag into the three layers of the library:
 *
 *   src/domain/schema/<resource>.ts               Effect schemas (+ shared.ts for cross-resource ones)
 *   src/application/operation/<resource>.ts       `<Resource>Operations` port interfaces
 *   src/infrastructure/http/operation/<resource>.ts  HttpClient adapters implementing those ports
 */
import { mkdir, readdir, rm } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import * as OpenApiGenerator from '@effect/openapi-generator/OpenApiGenerator'
import { Effect } from 'effect'
// TypeScript 7 (the native compiler) ships no JS API, so parsing uses the 6.x line.
import ts from 'typescript-api'

import { fileName, methodName, parseSchemaName, resourceKey, schemaName, typeName } from './naming.ts'
import { fetchSpec, normalizeSpec } from './spec.ts'

const root = join(import.meta.dir, '..')
const specPath = join(root, 'spec/openapi.json')
const dirs = {
	schema: join(root, 'src/domain/schema'),
	port: join(root, 'src/application/operation'),
	adapter: join(root, 'src/infrastructure/http/operation'),
}

const header = `/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
`

/**
 * Which aggregate API each tag belongs to. Everything not listed is Management API,
 * which is what a machine-to-machine client-credentials token can call.
 */
const surfaces: Record<Exclude<Surface, 'management'>, ReadonlyArray<string>> = {
	account: ['My account', 'Verifications'],
	experience: ['Experience'],
	public: ['Well-known', 'Status', 'Swagger.json', 'Authn', 'SAML applications auth flow'],
}
type Surface = 'management' | 'account' | 'experience' | 'public'
const surfaceOf = (tag: string): Surface =>
	(Object.entries(surfaces).find(([, tags]) => tags.includes(tag))?.[0] as Surface | undefined) ?? 'management'

// ---------------------------------------------------------------------------------------------
// 1. spec -> single generated source
// ---------------------------------------------------------------------------------------------

const fetchIndex = process.argv.indexOf('--fetch')
if (fetchIndex !== -1) {
	const endpoint = process.argv[fetchIndex + 1]
	if (!endpoint) throw new Error('--fetch requires a Logto endpoint, e.g. --fetch https://auth.example.com')
	// Pin the spec without the instance it was fetched from.
	const fetched = {
		...(await fetchSpec(endpoint)),
		servers: [{ url: 'https://your.logto.endpoint', description: 'Logto endpoint address.' }],
	}
	await Bun.write(specPath, `${JSON.stringify(fetched, null, '\t')}\n`)
	console.log(`✔ Fetched spec from ${endpoint}`)
}

const spec = await Bun.file(specPath).json()
const warnings: Array<string> = []
const source = await Effect.runPromise(
	Effect.gen(function* () {
		const generator = yield* OpenApiGenerator.OpenApiGenerator
		return yield* generator.generate(normalizeSpec(spec) as any, {
			name: 'LogtoClient',
			format: 'httpclient',
			onWarning: warning => warnings.push(`[${warning.code}] ${warning.operationId ?? warning.path ?? ''}: ${warning.message}`),
		})
	}).pipe(Effect.provide(OpenApiGenerator.layerTransformerSchema))
)
for (const warning of warnings) console.warn(`⚠ ${warning}`)

// ---------------------------------------------------------------------------------------------
// 2. parse the generated source
// ---------------------------------------------------------------------------------------------

type SchemaDecl = { name: string; order: number; type?: string; value?: string }
type OperationDecl = { id: string; tag: string; resource: string; method: string; doc: string; signature: string; implementation: string }

const file = ts.createSourceFile('generated.ts', source, ts.ScriptTarget.Latest, true)
const schemas = new Map<string, SchemaDecl>()
const implementations = new Map<string, string>()
const signatures = new Map<string, { doc: string; type: string }>()
const skip = new Set(['make', 'LogtoClientError', 'WithOptionalResponse'])

const declOf = (name: string) => {
	const existing = schemas.get(name)
	if (existing) return existing
	const decl: SchemaDecl = { name, order: schemas.size }
	schemas.set(name, decl)
	return decl
}

const propertyName = (name: ts.PropertyName) => (ts.isIdentifier(name) || ts.isStringLiteral(name) ? name.text : name.getText())

for (const statement of file.statements) {
	if (ts.isTypeAliasDeclaration(statement) && !skip.has(statement.name.text)) {
		declOf(statement.name.text).type = statement.getText()
	} else if (ts.isVariableStatement(statement)) {
		const [declaration] = statement.declarationList.declarations
		const name = declaration.name.getText()
		if (name === 'make') {
			collectImplementations(declaration)
		} else if (!skip.has(name)) {
			// Recursive definitions are emitted as private `__recursive_X` consts; export them so other files can reach them.
			declOf(name).value = statement.getText().replace(/^const /, 'export const ')
		}
	} else if (ts.isInterfaceDeclaration(statement) && statement.name.text === 'LogtoClient') {
		for (const member of statement.members) {
			if (!ts.isPropertySignature(member) || !member.type) continue
			const name = propertyName(member.name)
			if (name === 'httpClient') continue
			const doc = ts
				.getJSDocCommentsAndTags(member)
				.filter(ts.isJSDoc)
				.map(jsDoc => ts.getTextOfJSDocComment(jsDoc.comment) ?? '')
				.join('\n')
				.trim()
			signatures.set(name, { doc, type: member.type.getText() })
		}
	}
}

function collectImplementations(declaration: ts.VariableDeclaration) {
	const visit = (node: ts.Node): void => {
		if (ts.isReturnStatement(node) && node.expression && ts.isObjectLiteralExpression(node.expression)) {
			for (const property of node.expression.properties) {
				if (ts.isPropertyAssignment(property)) implementations.set(propertyName(property.name), property.initializer.getText())
			}
			return
		}
		ts.forEachChild(node, visit)
	}
	visit(declaration)
}

// ---------------------------------------------------------------------------------------------
// 3. model: operations grouped by resource, schema ownership, renames
// ---------------------------------------------------------------------------------------------

const tagByOperation = new Map<string, string>()
for (const item of Object.values<Record<string, any>>(spec.paths)) {
	for (const [verb, operation] of Object.entries<any>(item)) {
		if (verb === 'parameters' || !operation?.operationId) continue
		tagByOperation.set(operation.operationId[0].toUpperCase() + operation.operationId.slice(1), operation.tags?.[0] ?? 'Default')
	}
}

const operations: Array<OperationDecl> = []
for (const [id, implementation] of implementations) {
	const tag = tagByOperation.get(id)
	const signature = signatures.get(id)
	if (!tag || !signature) throw new Error(`Generated operation ${id} has no tag or signature`)
	operations.push({
		id,
		tag,
		resource: resourceKey(tag),
		method: methodName(id, tag),
		doc: signature.doc,
		signature: signature.type,
		implementation,
	})
}

const resources = new Map<string, { key: string; tag: string; operations: Array<OperationDecl> }>()
for (const operation of operations) {
	const resource = resources.get(operation.resource) ?? { key: operation.resource, tag: operation.tag, operations: [] }
	resource.operations.push(operation)
	resources.set(operation.resource, resource)
}
for (const resource of resources.values()) {
	const seen = new Set<string>()
	for (const operation of resource.operations) {
		if (seen.has(operation.method)) throw new Error(`Method name collision: ${resource.key}.${operation.method} (${operation.id})`)
		seen.add(operation.method)
	}
}

const IDENTIFIER = /\b[A-Z_][A-Za-z0-9_]*\b/g
const identifiers = (text: string) => new Set(text.match(IDENTIFIER) ?? [])
const schemaRefs = (text: string) => [...identifiers(text)].filter(name => schemas.has(name))

const dependencies = new Map<string, ReadonlyArray<string>>()
for (const decl of schemas.values()) {
	dependencies.set(
		decl.name,
		schemaRefs(`${decl.type ?? ''}\n${decl.value ?? ''}`).filter(name => name !== decl.name)
	)
}

const owners = new Map<string, Set<string>>()
const own = (name: string, resource: string) => {
	const set = owners.get(name) ?? new Set<string>()
	if (set.has(resource)) return
	set.add(resource)
	owners.set(name, set)
	for (const dependency of dependencies.get(name) ?? []) own(dependency, resource)
}
for (const operation of operations) {
	for (const name of schemaRefs(`${operation.signature}\n${operation.implementation}`)) own(name, operation.resource)
}

const SHARED = 'shared'
const ownerOf = (name: string) => {
	const set = owners.get(name)
	return set?.size === 1 ? [...set][0] : SHARED
}

const operationIds = new Set(operations.map(operation => operation.id))
const operationById = new Map(operations.map(operation => [operation.id, operation]))
const responseCounts = new Map<string, number>()
for (const name of schemas.keys()) {
	const parsed = parseSchemaName(name, operationIds)
	if (parsed?.role.kind === 'response') responseCounts.set(parsed.operationId, (responseCounts.get(parsed.operationId) ?? 0) + 1)
}

const renames = new Map<string, string>()
const namesByFile = new Map<string, Set<string>>()
for (const name of schemas.keys()) {
	const owner = ownerOf(name)
	const taken = namesByFile.get(owner) ?? new Set<string>()
	namesByFile.set(owner, taken)
	const parsed = parseSchemaName(name, operationIds)
	const operation = parsed && operationById.get(parsed.operationId)
	const candidate =
		parsed && operation && operation.resource === owner
			? schemaName(operation.method, parsed.role, responseCounts.get(parsed.operationId) ?? 1)
			: name
	const final = taken.has(candidate) ? name : candidate
	taken.add(final)
	if (final !== name) renames.set(name, final)
}

const nameOf = (name: string) => renames.get(name) ?? name
const rename = (text: string) => text.replace(IDENTIFIER, token => (schemas.has(token) ? nameOf(token) : token))

// ---------------------------------------------------------------------------------------------
// 4. text rewrites on generated fragments
// ---------------------------------------------------------------------------------------------

const count = (text: string, pattern: RegExp) => text.match(pattern)?.length ?? 0
const assertAbsent = (text: string, pattern: RegExp, context: string) => {
	if (pattern.test(text)) throw new Error(`${context}: unexpected ${pattern} left after rewrite`)
}

/** Logto's `search_params` is a bag of repeatable `search.*` / `mode.*` keys, not a record. */
const SEARCH_PARAMS_TYPE = /readonly "search_params"\?: \{ readonly \[x: string\]: string \}/g
const SEARCH_PARAMS_SCHEMA = /"search_params": Schema\.optionalKey\(Schema\.Record\(Schema\.String, Schema\.String\)\)/g
const SEARCH_PARAMS_URL = /(, )?"search_params": options\?\.params\?\.\["search_params"\] as any \}\),/g

const rewriteSchema = (text: string) =>
	rename(
		text
			.replace(SEARCH_PARAMS_TYPE, 'readonly "search_params"?: SearchParams')
			.replace(SEARCH_PARAMS_SCHEMA, '"search_params": Schema.optionalKey(SearchParams)')
	)

const rewriteImplementation = (operation: OperationDecl) => {
	const text = operation.implementation
		// Undocumented error statuses fall through to `unexpectedStatus`, which decodes Logto's error body.
		.replace(/^\s*"[45]\d\d": decodeVoidError\("[45]\d\d"\),?\n/gm, '')
		.replace(SEARCH_PARAMS_URL, ' }),\n    HttpClientRequest.appendUrlParams(searchParams(options?.params?.["search_params"])),')
		// Path parameters are interpolated raw by the generator; an id containing `/`, `?`, `#` or `..` would
		// otherwise address a different endpoint.
		.replace(/(HttpClientRequest\.\w+\(`)([^`]*)`/g, (_, call: string, path: string) => {
			assertAbsent(path.replace(/\$\{\w+\}/g, ''), /\$\{/, operation.id)
			// biome-ignore lint/suspicious/noTemplateCurlyInString: emits a template literal into generated code
			return `${call}${path.replace(/\$\{(\w+)\}/g, '${encodeURIComponent($1)}')}\``
		})
	assertAbsent(text, /decodeVoidError|decodeError|LogtoClientError|search_params"\] as any/, operation.id)
	return rename(text)
}

const rewriteSignature = (operation: OperationDecl) => {
	const text = operation.signature
		.replace(/typeof (\w+)\.(Encoded|Type)\b/g, '$1')
		.replace(/HttpClientError\.HttpClientError \| SchemaError(?: \| LogtoClientError<"\d+", [^>]+>)*/g, 'LogtoError')
	assertAbsent(text, /HttpClientError|SchemaError|LogtoClientError|typeof /, operation.id)
	return rename(text)
}

// ---------------------------------------------------------------------------------------------
// 5. emit
// ---------------------------------------------------------------------------------------------

const written: Array<string> = []
const write = async (path: string, content: string) => {
	await mkdir(dirname(path), { recursive: true })
	await Bun.write(path, content)
	written.push(path)
}

const importPath = (from: string, to: string) => {
	// Explicit `.ts` extensions: `rewriteRelativeImportExtensions` turns them into `.js` on build.
	const path = relative(dirname(from), to)
	return path.startsWith('.') ? path : `./${path}`
}

const namedImport = (names: Iterable<string>, from: string, to: string, typeOnly = false) => {
	const sorted = [...new Set(names)].sort()
	return sorted.length ? `import ${typeOnly ? 'type ' : ''}{ ${sorted.join(', ')} } from '${importPath(from, to)}';\n` : ''
}

for (const dir of Object.values(dirs)) {
	await mkdir(dir, { recursive: true })
	for (const entry of await readdir(dir)) if (entry.endsWith('.ts')) await rm(join(dir, entry))
}

const schemaFile = (owner: string) => join(dirs.schema, `${owner === SHARED ? SHARED : fileName(owner)}.ts`)
const searchParamsFile = join(root, 'src/domain/search/search-params.ts')

/** Splits referenced (original) schema names into local ones and imports from other schema files. */
const importsFor = (names: Iterable<string>, owner: string, from: string, typeOnly: boolean) => {
	const byOwner = new Map<string, Set<string>>()
	for (const name of names) {
		const target = ownerOf(name)
		if (target === owner && from === schemaFile(owner)) continue
		const set = byOwner.get(target) ?? new Set<string>()
		set.add(nameOf(name))
		byOwner.set(target, set)
	}
	return [...byOwner.entries()]
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([target, set]) => namedImport(set, from, schemaFile(target), typeOnly))
		.join('')
}

// domain/schema/*
const schemasByOwner = new Map<string, Array<SchemaDecl>>()
for (const decl of [...schemas.values()].sort((a, b) => a.order - b.order)) {
	const owner = ownerOf(decl.name)
	schemasByOwner.set(owner, [...(schemasByOwner.get(owner) ?? []), decl])
}
for (const [owner, decls] of schemasByOwner) {
	const path = schemaFile(owner)
	const body = decls
		.map(decl =>
			[decl.type, decl.value]
				.filter(Boolean)
				.map(text => rewriteSchema(text!))
				.join('\n')
		)
		.join('\n\n')
	const external = new Set(decls.flatMap(decl => dependencies.get(decl.name) ?? []).filter(name => ownerOf(name) !== owner))
	const usesSearchParams = body.includes('SearchParams')
	await write(
		path,
		`${header}import * as Schema from 'effect/Schema';\n${usesSearchParams ? namedImport(['SearchParams'], path, searchParamsFile) : ''}${importsFor(external, owner, path, false)}\n${body}\n`
	)
}

const ordered = [...resources.values()].sort((a, b) => a.key.localeCompare(b.key))
await write(
	join(dirs.schema, 'index.ts'),
	`${header}${ordered
		.filter(resource => schemasByOwner.has(resource.key))
		.map(resource => `export * as ${typeName(resource.key)} from './${fileName(resource.key)}.ts';`)
		.join('\n')}\n${schemasByOwner.has(SHARED) ? "export * from './shared.ts';\n" : ''}`
)

// application/operation/* and infrastructure/http/operation/*
const configFile = join(root, 'src/application/config.ts')
const transportFile = join(root, 'src/infrastructure/http/transport.ts')
const interfaceName = (key: string) => `${typeName(key)}Operations`
const factoryName = (key: string) => `make${typeName(key)}`

const doc = (text: string, indent: string) =>
	text
		? `${indent}/**\n${text
				.split('\n')
				.map(line => `${indent} *${line ? ` ${line}` : ''}`)
				.join('\n')}\n${indent} */\n`
		: ''

for (const resource of ordered) {
	const portPath = join(dirs.port, `${fileName(resource.key)}.ts`)
	const adapterPath = join(dirs.adapter, `${fileName(resource.key)}.ts`)

	const members = resource.operations.map(
		operation => `${doc(operation.doc, '\t')}\treadonly ${operation.method}: ${rewriteSignature(operation)};`
	)
	const portRefs = resource.operations.flatMap(operation => schemaRefs(operation.signature))
	await write(
		portPath,
		`${header}import type * as Effect from 'effect/Effect';\n\n${namedImport(['LogtoError', 'OperationConfig', 'WithOptionalResponse'], portPath, configFile, true)}${importsFor(portRefs, resource.key, portPath, true)}
/**
 * Logto \`${resource.tag}\` endpoints.
 */
export interface ${interfaceName(resource.key)} {
${members.join('\n')}
}
`
	)

	const bodies = resource.operations.map(operation => `\t${operation.method}: ${rewriteImplementation(operation)},`)
	const adapterText = bodies.join('\n')
	const adapterRefs = resource.operations.flatMap(operation => schemaRefs(operation.implementation))
	await write(
		adapterPath,
		`${header}${adapterText.includes('Effect.') ? "import * as Effect from 'effect/Effect';\n" : ''}import * as HttpClientRequest from 'effect/unstable/http/HttpClientRequest';
import * as HttpClientResponse from 'effect/unstable/http/HttpClientResponse';

${namedImport([interfaceName(resource.key)], adapterPath, portPath, true)}${importsFor(adapterRefs, resource.key, adapterPath, false)}${namedImport(['Transport'], adapterPath, transportFile, true)}
export const ${factoryName(resource.key)} = ({ withResponse, decodeSuccess, unexpectedStatus, searchParams }: Transport): ${interfaceName(resource.key)} => ({
${adapterText}
});
`
	)
}

const bySurface = (surface: Surface) => ordered.filter(resource => surfaceOf(resource.tag) === surface)
const surfaceNames: Record<Surface, { api: string; summary: string }> = {
	management: {
		api: 'LogtoManagementApi',
		summary: 'Management API — callable with a machine-to-machine (client credentials) access token.',
	},
	account: { api: 'LogtoAccountApi', summary: 'Account API — callable with an end-user access token.' },
	experience: { api: 'LogtoExperienceApi', summary: 'Experience API — drives sign-in/registration interactions from a custom UI.' },
	public: { api: 'LogtoPublicApi', summary: 'Unauthenticated and protocol endpoints.' },
}
const surfaceList = Object.keys(surfaceNames) as Array<Surface>

await write(
	join(dirs.port, 'index.ts'),
	`${header}${ordered.map(resource => `import type { ${interfaceName(resource.key)} } from './${fileName(resource.key)}.ts';`).join('\n')}

export type { ${ordered.map(resource => interfaceName(resource.key)).join(', ')} };
${surfaceList
	.map(
		surface => `
/**
 * ${surfaceNames[surface].summary}
 */
export interface ${surfaceNames[surface].api} {
${bySurface(surface)
	.map(resource => `\treadonly ${resource.key}: ${interfaceName(resource.key)};`)
	.join('\n')}
}
`
	)
	.join('')}`
)

await write(
	join(dirs.adapter, 'index.ts'),
	`${header}import type { ${surfaceList.map(surface => surfaceNames[surface].api).join(', ')} } from '${importPath(join(dirs.adapter, 'index.ts'), join(dirs.port, 'index.ts'))}';
import type { Transport } from '../transport.ts';
${ordered.map(resource => `import { ${factoryName(resource.key)} } from './${fileName(resource.key)}.ts';`).join('\n')}
${surfaceList
	.map(
		surface => `
export const make${surfaceNames[surface].api.replace(/^Logto/, '')} = (transport: Transport): ${surfaceNames[surface].api} => ({
${bySurface(surface)
	.map(resource => `\t${resource.key}: ${factoryName(resource.key)}(transport),`)
	.join('\n')}
});
`
	)
	.join('')}`
)

// ---------------------------------------------------------------------------------------------
// 6. format + report
// ---------------------------------------------------------------------------------------------

// Formats and applies Biome's safe lint fixes (regex literals, literal keys) to the generated code.
const biome = Bun.spawnSync(['bunx', 'biome', 'check', '--write', '--diagnostic-level=error', ...Object.values(dirs)], {
	cwd: join(root, '../..'),
	stdout: 'inherit',
	stderr: 'inherit',
})
if (biome.exitCode !== 0) throw new Error(`biome exited with ${biome.exitCode}`)

const searchRewrites = count(source, SEARCH_PARAMS_URL)
console.log(
	`✔ ${operations.length} operations in ${resources.size} resources, ${schemas.size} schemas (${schemasByOwner.get(SHARED)?.length ?? 0} shared, ${renames.size} renamed), ${searchRewrites} search-enabled lists`
)
console.log(`✔ Wrote ${written.length} files`)
