/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Schema from 'effect/Schema'

export type GetHasuraAuthParams = { readonly resource: string; readonly unauthorizedRole?: string }
export const GetHasuraAuthParams = Schema.Struct({
	resource: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })),
	unauthorizedRole: Schema.optionalKey(Schema.String),
})

export type GetHasuraAuthResponse = { readonly 'X-Hasura-User-Id'?: string; readonly 'X-Hasura-Role'?: string }
export const GetHasuraAuthResponse = Schema.Struct({
	'X-Hasura-User-Id': Schema.optionalKey(Schema.String),
	'X-Hasura-Role': Schema.optionalKey(Schema.String),
})

export type AssertSamlPayload = { readonly [x: string]: Schema.Json }
export const AssertSamlPayload = Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' })).annotate({
	description: 'arbitrary',
})

export type AssertSingleSignOnSamlPayload = { readonly RelayState?: string; readonly SAMLResponse: string }
export const AssertSingleSignOnSamlPayload = Schema.Struct({
	RelayState: Schema.optionalKey(
		Schema.String.annotate({
			description:
				"SAML standard parameter that will be transmitted between the identity provider and the service provider. It will be used as the session ID (jti) of the user's Logto authentication session. This API will use this session ID to retrieve the SSO connector authentication session from the database.",
		})
	),
	SAMLResponse: Schema.String.annotate({ description: 'The SAML assertion response from the identity provider (IdP).' }),
})
