/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Schema from 'effect/Schema'

export type ListResponse = ReadonlyArray<{
	readonly type: 'Email' | 'Sms' | 'Social'
	readonly isDemo?: boolean
	readonly id: string
	readonly target: string
	readonly name: { readonly [x: string]: Schema.Json }
	readonly description: { readonly [x: string]: Schema.Json }
	readonly logo: string
	readonly logoDark: string | null
	readonly readme: string
	readonly configTemplate?: string
	readonly formItems?: ReadonlyArray<
		| {
				readonly type: string
				readonly selectItems: ReadonlyArray<{ readonly value: string; readonly title: string }>
				readonly key: string
				readonly label: string
				readonly placeholder?: string
				readonly required?: boolean
				readonly defaultValue?: Schema.Json
				readonly showConditions?: ReadonlyArray<{ readonly targetKey: string; readonly expectValue?: Schema.Json }>
				readonly description?: string
				readonly tooltip?: string
				readonly isConfidential?: boolean
				readonly isDevFeature?: boolean
		  }
		| {
				readonly type: string
				readonly selectItems: ReadonlyArray<{ readonly value: string }>
				readonly key: string
				readonly label: string
				readonly placeholder?: string
				readonly required?: boolean
				readonly defaultValue?: Schema.Json
				readonly showConditions?: ReadonlyArray<{ readonly targetKey: string; readonly expectValue?: Schema.Json }>
				readonly description?: string
				readonly tooltip?: string
				readonly isConfidential?: boolean
				readonly isDevFeature?: boolean
		  }
		| {
				readonly type: 'Text' | 'Number' | 'MultilineText' | 'Switch' | 'Json'
				readonly key: string
				readonly label: string
				readonly placeholder?: string
				readonly required?: boolean
				readonly defaultValue?: Schema.Json
				readonly showConditions?: ReadonlyArray<{ readonly targetKey: string; readonly expectValue?: Schema.Json }>
				readonly description?: string
				readonly tooltip?: string
				readonly isConfidential?: boolean
				readonly isDevFeature?: boolean
		  }
	>
	readonly customData?: { readonly [x: string]: Schema.Json }
	readonly fromEmail?: string
	readonly platform: 'Native' | 'Universal' | 'Web' | null
	readonly isStandard?: boolean
	readonly isTokenStorageSupported?: boolean
}>
export const ListResponse = Schema.Array(
	Schema.Struct({
		type: Schema.Literals(['Email', 'Sms', 'Social']),
		isDemo: Schema.optionalKey(Schema.Boolean),
		id: Schema.String,
		target: Schema.String,
		name: Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' })).annotate({
			description: 'Validator function',
		}),
		description: Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' })).annotate({
			description: 'Validator function',
		}),
		logo: Schema.String,
		logoDark: Schema.Union([Schema.String, Schema.Null]),
		readme: Schema.String,
		configTemplate: Schema.optionalKey(Schema.String),
		formItems: Schema.optionalKey(
			Schema.Array(
				Schema.Union(
					[
						Schema.Struct({
							type: Schema.String.annotate({ format: '"Select"' }),
							selectItems: Schema.Array(Schema.Struct({ value: Schema.String, title: Schema.String })),
							key: Schema.String,
							label: Schema.String,
							placeholder: Schema.optionalKey(Schema.String),
							required: Schema.optionalKey(Schema.Boolean),
							defaultValue: Schema.optionalKey(Schema.Json.annotate({ expected: 'JSON value', examples: [{}] })),
							showConditions: Schema.optionalKey(
								Schema.Array(
									Schema.Struct({
										targetKey: Schema.String,
										expectValue: Schema.optionalKey(Schema.Json.annotate({ expected: 'JSON value', examples: [{}] })),
									})
								)
							),
							description: Schema.optionalKey(Schema.String),
							tooltip: Schema.optionalKey(Schema.String),
							isConfidential: Schema.optionalKey(Schema.Boolean),
							isDevFeature: Schema.optionalKey(Schema.Boolean),
						}),
						Schema.Struct({
							type: Schema.String.annotate({ format: '"MultiSelect"' }),
							selectItems: Schema.Array(Schema.Struct({ value: Schema.String })),
							key: Schema.String,
							label: Schema.String,
							placeholder: Schema.optionalKey(Schema.String),
							required: Schema.optionalKey(Schema.Boolean),
							defaultValue: Schema.optionalKey(Schema.Json.annotate({ expected: 'JSON value', examples: [{}] })),
							showConditions: Schema.optionalKey(
								Schema.Array(
									Schema.Struct({
										targetKey: Schema.String,
										expectValue: Schema.optionalKey(Schema.Json.annotate({ expected: 'JSON value', examples: [{}] })),
									})
								)
							),
							description: Schema.optionalKey(Schema.String),
							tooltip: Schema.optionalKey(Schema.String),
							isConfidential: Schema.optionalKey(Schema.Boolean),
							isDevFeature: Schema.optionalKey(Schema.Boolean),
						}),
						Schema.Struct({
							type: Schema.Literals(['Text', 'Number', 'MultilineText', 'Switch', 'Json']),
							key: Schema.String,
							label: Schema.String,
							placeholder: Schema.optionalKey(Schema.String),
							required: Schema.optionalKey(Schema.Boolean),
							defaultValue: Schema.optionalKey(Schema.Json.annotate({ expected: 'JSON value', examples: [{}] })),
							showConditions: Schema.optionalKey(
								Schema.Array(
									Schema.Struct({
										targetKey: Schema.String,
										expectValue: Schema.optionalKey(Schema.Json.annotate({ expected: 'JSON value', examples: [{}] })),
									})
								)
							),
							description: Schema.optionalKey(Schema.String),
							tooltip: Schema.optionalKey(Schema.String),
							isConfidential: Schema.optionalKey(Schema.Boolean),
							isDevFeature: Schema.optionalKey(Schema.Boolean),
						}),
					],
					{ mode: 'oneOf' }
				)
			)
		),
		customData: Schema.optionalKey(Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value', examples: [{}] }))),
		fromEmail: Schema.optionalKey(Schema.String),
		platform: Schema.Union([Schema.Literals(['Native', 'Universal', 'Web']), Schema.Null], { mode: 'oneOf' }),
		isStandard: Schema.optionalKey(Schema.Boolean),
		isTokenStorageSupported: Schema.optionalKey(Schema.Boolean),
	})
)

export type GetResponse = {
	readonly type: 'Email' | 'Sms' | 'Social'
	readonly isDemo?: boolean
	readonly id: string
	readonly target: string
	readonly name: { readonly [x: string]: Schema.Json }
	readonly description: { readonly [x: string]: Schema.Json }
	readonly logo: string
	readonly logoDark: string | null
	readonly readme: string
	readonly configTemplate?: string
	readonly formItems?: ReadonlyArray<
		| {
				readonly type: string
				readonly selectItems: ReadonlyArray<{ readonly value: string; readonly title: string }>
				readonly key: string
				readonly label: string
				readonly placeholder?: string
				readonly required?: boolean
				readonly defaultValue?: Schema.Json
				readonly showConditions?: ReadonlyArray<{ readonly targetKey: string; readonly expectValue?: Schema.Json }>
				readonly description?: string
				readonly tooltip?: string
				readonly isConfidential?: boolean
				readonly isDevFeature?: boolean
		  }
		| {
				readonly type: string
				readonly selectItems: ReadonlyArray<{ readonly value: string }>
				readonly key: string
				readonly label: string
				readonly placeholder?: string
				readonly required?: boolean
				readonly defaultValue?: Schema.Json
				readonly showConditions?: ReadonlyArray<{ readonly targetKey: string; readonly expectValue?: Schema.Json }>
				readonly description?: string
				readonly tooltip?: string
				readonly isConfidential?: boolean
				readonly isDevFeature?: boolean
		  }
		| {
				readonly type: 'Text' | 'Number' | 'MultilineText' | 'Switch' | 'Json'
				readonly key: string
				readonly label: string
				readonly placeholder?: string
				readonly required?: boolean
				readonly defaultValue?: Schema.Json
				readonly showConditions?: ReadonlyArray<{ readonly targetKey: string; readonly expectValue?: Schema.Json }>
				readonly description?: string
				readonly tooltip?: string
				readonly isConfidential?: boolean
				readonly isDevFeature?: boolean
		  }
	>
	readonly customData?: { readonly [x: string]: Schema.Json }
	readonly fromEmail?: string
	readonly platform: 'Native' | 'Universal' | 'Web' | null
	readonly isStandard?: boolean
	readonly isTokenStorageSupported?: boolean
}
export const GetResponse = Schema.Struct({
	type: Schema.Literals(['Email', 'Sms', 'Social']),
	isDemo: Schema.optionalKey(Schema.Boolean),
	id: Schema.String,
	target: Schema.String,
	name: Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' })).annotate({ description: 'Validator function' }),
	description: Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' })).annotate({
		description: 'Validator function',
	}),
	logo: Schema.String,
	logoDark: Schema.Union([Schema.String, Schema.Null]),
	readme: Schema.String,
	configTemplate: Schema.optionalKey(Schema.String),
	formItems: Schema.optionalKey(
		Schema.Array(
			Schema.Union(
				[
					Schema.Struct({
						type: Schema.String.annotate({ format: '"Select"' }),
						selectItems: Schema.Array(Schema.Struct({ value: Schema.String, title: Schema.String })),
						key: Schema.String,
						label: Schema.String,
						placeholder: Schema.optionalKey(Schema.String),
						required: Schema.optionalKey(Schema.Boolean),
						defaultValue: Schema.optionalKey(Schema.Json.annotate({ expected: 'JSON value', examples: [{}] })),
						showConditions: Schema.optionalKey(
							Schema.Array(
								Schema.Struct({
									targetKey: Schema.String,
									expectValue: Schema.optionalKey(Schema.Json.annotate({ expected: 'JSON value', examples: [{}] })),
								})
							)
						),
						description: Schema.optionalKey(Schema.String),
						tooltip: Schema.optionalKey(Schema.String),
						isConfidential: Schema.optionalKey(Schema.Boolean),
						isDevFeature: Schema.optionalKey(Schema.Boolean),
					}),
					Schema.Struct({
						type: Schema.String.annotate({ format: '"MultiSelect"' }),
						selectItems: Schema.Array(Schema.Struct({ value: Schema.String })),
						key: Schema.String,
						label: Schema.String,
						placeholder: Schema.optionalKey(Schema.String),
						required: Schema.optionalKey(Schema.Boolean),
						defaultValue: Schema.optionalKey(Schema.Json.annotate({ expected: 'JSON value', examples: [{}] })),
						showConditions: Schema.optionalKey(
							Schema.Array(
								Schema.Struct({
									targetKey: Schema.String,
									expectValue: Schema.optionalKey(Schema.Json.annotate({ expected: 'JSON value', examples: [{}] })),
								})
							)
						),
						description: Schema.optionalKey(Schema.String),
						tooltip: Schema.optionalKey(Schema.String),
						isConfidential: Schema.optionalKey(Schema.Boolean),
						isDevFeature: Schema.optionalKey(Schema.Boolean),
					}),
					Schema.Struct({
						type: Schema.Literals(['Text', 'Number', 'MultilineText', 'Switch', 'Json']),
						key: Schema.String,
						label: Schema.String,
						placeholder: Schema.optionalKey(Schema.String),
						required: Schema.optionalKey(Schema.Boolean),
						defaultValue: Schema.optionalKey(Schema.Json.annotate({ expected: 'JSON value', examples: [{}] })),
						showConditions: Schema.optionalKey(
							Schema.Array(
								Schema.Struct({
									targetKey: Schema.String,
									expectValue: Schema.optionalKey(Schema.Json.annotate({ expected: 'JSON value', examples: [{}] })),
								})
							)
						),
						description: Schema.optionalKey(Schema.String),
						tooltip: Schema.optionalKey(Schema.String),
						isConfidential: Schema.optionalKey(Schema.Boolean),
						isDevFeature: Schema.optionalKey(Schema.Boolean),
					}),
				],
				{ mode: 'oneOf' }
			)
		)
	),
	customData: Schema.optionalKey(Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value', examples: [{}] }))),
	fromEmail: Schema.optionalKey(Schema.String),
	platform: Schema.Union([Schema.Literals(['Native', 'Universal', 'Web']), Schema.Null], { mode: 'oneOf' }),
	isStandard: Schema.optionalKey(Schema.Boolean),
	isTokenStorageSupported: Schema.optionalKey(Schema.Boolean),
})
