/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Schema from 'effect/Schema'

export type TranslationObject = { readonly [x: string]: Translation }
export const TranslationObject = Schema.suspend((): Schema.Codec<TranslationObject> => __recursive_TranslationObject)

export type Translation = string | TranslationObject
export const Translation = Schema.Union([Schema.String, Schema.suspend((): Schema.Codec<TranslationObject> => TranslationObject)], {
	mode: 'oneOf',
}).annotate({ identifier: 'Translation' })

export const __recursive_TranslationObject = Schema.Record(
	Schema.String,
	Schema.suspend((): Schema.Codec<Translation> => Translation)
).annotate({
	examples: [{ input: { username: 'Username', password: 'Password' }, action: { sign_in: 'Sign In', continue: 'Continue' } }],
	identifier: 'TranslationObject',
})

export type ListResponse = ReadonlyArray<{
	readonly tenantId: string
	readonly id: string
	readonly languageTag: string
	readonly translation: TranslationObject
}>
export const ListResponse = Schema.Array(
	Schema.Struct({
		tenantId: Schema.String.check(Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })),
		id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })
		),
		languageTag: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxLength(16).annotate({ expected: 'a value with a length of at most 16' })
		),
		translation: TranslationObject,
	})
)

export type GetResponse = {
	readonly tenantId: string
	readonly id: string
	readonly languageTag: string
	readonly translation: TranslationObject
}
export const GetResponse = Schema.Struct({
	tenantId: Schema.String.check(Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })),
	id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
		Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })
	),
	languageTag: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
		Schema.isMaxLength(16).annotate({ expected: 'a value with a length of at most 16' })
	),
	translation: TranslationObject,
})

export type ReplacePayload = TranslationObject
export const ReplacePayload = TranslationObject

export type ReplaceResponse = {
	readonly tenantId: string
	readonly id: string
	readonly languageTag: string
	readonly translation: TranslationObject
}
export const ReplaceResponse = Schema.Struct({
	tenantId: Schema.String.check(Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })),
	id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
		Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })
	),
	languageTag: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
		Schema.isMaxLength(16).annotate({ expected: 'a value with a length of at most 16' })
	),
	translation: TranslationObject,
})
