/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Schema from 'effect/Schema'

export type ListParams = { readonly q?: string; readonly page?: number; readonly page_size?: number }
export const ListParams = Schema.Struct({
	q: Schema.optionalKey(Schema.String),
	page: Schema.optionalKey(
		Schema.Number.annotate({ default: 1 })
			.check(Schema.isInt().annotate({ expected: 'an integer' }))
			.check(Schema.isGreaterThanOrEqualTo(1).annotate({ expected: 'a value greater than or equal to 1' }))
	),
	page_size: Schema.optionalKey(
		Schema.Number.annotate({ default: 20 })
			.check(Schema.isInt().annotate({ expected: 'an integer' }))
			.check(Schema.isGreaterThanOrEqualTo(1).annotate({ expected: 'a value greater than or equal to 1' }))
	),
})

export type ListResponse = ReadonlyArray<{
	readonly tenantId: string
	readonly id: string
	readonly name: string
	readonly description: string | null
}>
export const ListResponse = Schema.Array(
	Schema.Struct({
		tenantId: Schema.String.check(Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })),
		id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })
		),
		name: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxLength(128).annotate({ expected: 'a value with a length of at most 128' })
		),
		description: Schema.Union([
			Schema.String.check(Schema.isMaxLength(256).annotate({ expected: 'a value with a length of at most 256' })),
			Schema.Null,
		]),
	})
)

export type CreatePayload = { readonly tenantId?: string; readonly name: string; readonly description?: string | null }
export const CreatePayload = Schema.Struct({
	tenantId: Schema.optionalKey(Schema.String.check(Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' }))),
	name: Schema.String.annotate({ description: 'The name of the organization scope. It must be unique within the organization template.' })
		.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' }))
		.check(Schema.isMaxLength(128).annotate({ expected: 'a value with a length of at most 128' })),
	description: Schema.optionalKey(
		Schema.Union([
			Schema.String.check(Schema.isMaxLength(256).annotate({ expected: 'a value with a length of at most 256' })),
			Schema.Null,
		]).annotate({ description: 'The description of the organization scope.' })
	),
})

export type CreateResponse = { readonly tenantId: string; readonly id: string; readonly name: string; readonly description: string | null }
export const CreateResponse = Schema.Struct({
	tenantId: Schema.String.check(Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })),
	id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
		Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })
	),
	name: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
		Schema.isMaxLength(128).annotate({ expected: 'a value with a length of at most 128' })
	),
	description: Schema.Union([
		Schema.String.check(Schema.isMaxLength(256).annotate({ expected: 'a value with a length of at most 256' })),
		Schema.Null,
	]),
})

export type GetResponse = { readonly tenantId: string; readonly id: string; readonly name: string; readonly description: string | null }
export const GetResponse = Schema.Struct({
	tenantId: Schema.String.check(Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })),
	id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
		Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })
	),
	name: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
		Schema.isMaxLength(128).annotate({ expected: 'a value with a length of at most 128' })
	),
	description: Schema.Union([
		Schema.String.check(Schema.isMaxLength(256).annotate({ expected: 'a value with a length of at most 256' })),
		Schema.Null,
	]),
})

export type UpdatePayload = { readonly tenantId?: string; readonly name?: string; readonly description?: string | null }
export const UpdatePayload = Schema.Struct({
	tenantId: Schema.optionalKey(Schema.String.check(Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' }))),
	name: Schema.optionalKey(
		Schema.String.annotate({
			description: 'The updated name of the organization scope. It must be unique within the organization template.',
		})
			.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' }))
			.check(Schema.isMaxLength(128).annotate({ expected: 'a value with a length of at most 128' }))
	),
	description: Schema.optionalKey(
		Schema.Union([
			Schema.String.check(Schema.isMaxLength(256).annotate({ expected: 'a value with a length of at most 256' })),
			Schema.Null,
		]).annotate({ description: 'The updated description of the organization scope.' })
	),
})

export type UpdateResponse = { readonly tenantId: string; readonly id: string; readonly name: string; readonly description: string | null }
export const UpdateResponse = Schema.Struct({
	tenantId: Schema.String.check(Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })),
	id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
		Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })
	),
	name: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
		Schema.isMaxLength(128).annotate({ expected: 'a value with a length of at most 128' })
	),
	description: Schema.Union([
		Schema.String.check(Schema.isMaxLength(256).annotate({ expected: 'a value with a length of at most 256' })),
		Schema.Null,
	]),
})
