/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Schema from 'effect/Schema'
import { SearchParams } from '../search/search-params.ts'

export type ListParams = { readonly includeScopes?: string; readonly page?: number; readonly page_size?: number }
export const ListParams = Schema.Struct({
	includeScopes: Schema.optionalKey(Schema.String),
	page: Schema.optionalKey(
		Schema.Number.annotate({ default: 1 })
			.check(Schema.isInt().annotate({ expected: 'an integer' }))
			.check(Schema.isGreaterThanOrEqualTo(1).annotate({ expected: 'a value greater than or equal to 1' }))
	),
	page_size: Schema.optionalKey(
		Schema.Number.annotate({ default: 20 })
			.check(Schema.isInt().annotate({ expected: 'an integer' }))
			.check(Schema.isGreaterThanOrEqualTo(1).annotate({ expected: 'a value greater than or equal to 1' }))
	),
})

export type ListResponse = ReadonlyArray<
	{
		readonly tenantId: string
		readonly id: string
		readonly name: string
		readonly indicator: string
		readonly isDefault: boolean
		readonly accessTokenTtl: number
		readonly scopes?: ReadonlyArray<
			{
				readonly tenantId: string
				readonly id: string
				readonly resourceId: string
				readonly name: string
				readonly description: string | null
				readonly createdAt: number
			} & { readonly [x: string]: Schema.Json }
		>
	} & { readonly [x: string]: Schema.Json }
>
export const ListResponse = Schema.Array(
	Schema.StructWithRest(
		Schema.Struct({
			tenantId: Schema.String.check(Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })),
			id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
				Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
			),
			name: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })),
			indicator: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })),
			isDefault: Schema.Boolean,
			accessTokenTtl: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
			scopes: Schema.optionalKey(
				Schema.Array(
					Schema.StructWithRest(
						Schema.Struct({
							tenantId: Schema.String.check(
								Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
							),
							id: Schema.String.check(
								Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })
							).check(Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })),
							resourceId: Schema.String.check(
								Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })
							).check(Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })),
							name: Schema.String.check(
								Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })
							).check(Schema.isMaxCodePoints(256).annotate({ expected: 'a string with at most 256 code points' })),
							description: Schema.Union([Schema.String, Schema.Null]),
							createdAt: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
						}),
						[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
					)
				)
			),
		}),
		[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
	)
)

export type CreatePayload = {
	readonly tenantId?: string
	readonly name: string
	readonly indicator: string
	readonly accessTokenTtl?: number
} & { readonly [x: string]: Schema.Json }
export const CreatePayload = Schema.StructWithRest(
	Schema.Struct({
		tenantId: Schema.optionalKey(
			Schema.String.check(Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' }))
		),
		name: Schema.String.annotate({ description: 'The name of the resource.' }).check(
			Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })
		),
		indicator: Schema.String.annotate({ description: 'The unique resource indicator. Should be a valid URI.' }).check(
			Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })
		),
		accessTokenTtl: Schema.optionalKey(
			Schema.Number.annotate({
				description: 'The access token TTL in seconds. It affects the `exp` claim of the access token granted for this resource.',
				default: 3600,
			}).check(Schema.isFinite().annotate({ expected: 'a finite number' }))
		),
	}),
	[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
)

export type CreateResponse = {
	readonly tenantId: string
	readonly id: string
	readonly name: string
	readonly indicator: string
	readonly isDefault: boolean
	readonly accessTokenTtl: number
	readonly scopes?: ReadonlyArray<
		{
			readonly tenantId: string
			readonly id: string
			readonly resourceId: string
			readonly name: string
			readonly description: string | null
			readonly createdAt: number
		} & { readonly [x: string]: Schema.Json }
	>
} & { readonly [x: string]: Schema.Json }
export const CreateResponse = Schema.StructWithRest(
	Schema.Struct({
		tenantId: Schema.String.check(Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })),
		id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
		),
		name: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })),
		indicator: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })),
		isDefault: Schema.Boolean,
		accessTokenTtl: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
		scopes: Schema.optionalKey(
			Schema.Array(
				Schema.StructWithRest(
					Schema.Struct({
						tenantId: Schema.String.check(
							Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
						),
						id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
							Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
						),
						resourceId: Schema.String.check(
							Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })
						).check(Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })),
						name: Schema.String.check(
							Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })
						).check(Schema.isMaxCodePoints(256).annotate({ expected: 'a string with at most 256 code points' })),
						description: Schema.Union([Schema.String, Schema.Null]),
						createdAt: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
					}),
					[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
				)
			)
		),
	}),
	[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
)

export type GetResponse = {
	readonly tenantId: string
	readonly id: string
	readonly name: string
	readonly indicator: string
	readonly isDefault: boolean
	readonly accessTokenTtl: number
} & { readonly [x: string]: Schema.Json }
export const GetResponse = Schema.StructWithRest(
	Schema.Struct({
		tenantId: Schema.String.check(Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })),
		id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
		),
		name: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })),
		indicator: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })),
		isDefault: Schema.Boolean,
		accessTokenTtl: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
	}),
	[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
)

export type UpdatePayload = { readonly tenantId?: string; readonly name?: string; readonly accessTokenTtl?: number } & {
	readonly [x: string]: Schema.Json
}
export const UpdatePayload = Schema.StructWithRest(
	Schema.Struct({
		tenantId: Schema.optionalKey(
			Schema.String.check(Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' }))
		),
		name: Schema.optionalKey(
			Schema.String.annotate({ description: 'The updated name of the resource.' }).check(
				Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })
			)
		),
		accessTokenTtl: Schema.optionalKey(
			Schema.Number.annotate({ description: 'The updated access token TTL in seconds.' }).check(
				Schema.isFinite().annotate({ expected: 'a finite number' })
			)
		),
	}),
	[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
)

export type UpdateResponse = {
	readonly tenantId: string
	readonly id: string
	readonly name: string
	readonly indicator: string
	readonly isDefault: boolean
	readonly accessTokenTtl: number
} & { readonly [x: string]: Schema.Json }
export const UpdateResponse = Schema.StructWithRest(
	Schema.Struct({
		tenantId: Schema.String.check(Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })),
		id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
		),
		name: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })),
		indicator: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })),
		isDefault: Schema.Boolean,
		accessTokenTtl: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
	}),
	[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
)

export type UpdateIsDefaultPayload = { readonly isDefault: boolean } & { readonly [x: string]: Schema.Json }
export const UpdateIsDefaultPayload = Schema.StructWithRest(
	Schema.Struct({ isDefault: Schema.Boolean.annotate({ description: 'The updated value of the `isDefault` property.' }) }),
	[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
)

export type UpdateIsDefaultResponse = {
	readonly tenantId: string
	readonly id: string
	readonly name: string
	readonly indicator: string
	readonly isDefault: boolean
	readonly accessTokenTtl: number
} & { readonly [x: string]: Schema.Json }
export const UpdateIsDefaultResponse = Schema.StructWithRest(
	Schema.Struct({
		tenantId: Schema.String.check(Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })),
		id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
		),
		name: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })),
		indicator: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })),
		isDefault: Schema.Boolean,
		accessTokenTtl: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
	}),
	[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
)

export type ListScopesParams = { readonly page?: number; readonly page_size?: number; readonly search_params?: SearchParams }
export const ListScopesParams = Schema.Struct({
	page: Schema.optionalKey(
		Schema.Number.annotate({ default: 1 })
			.check(Schema.isInt().annotate({ expected: 'an integer' }))
			.check(Schema.isGreaterThanOrEqualTo(1).annotate({ expected: 'a value greater than or equal to 1' }))
	),
	page_size: Schema.optionalKey(
		Schema.Number.annotate({ default: 20 })
			.check(Schema.isInt().annotate({ expected: 'an integer' }))
			.check(Schema.isGreaterThanOrEqualTo(1).annotate({ expected: 'a value greater than or equal to 1' }))
	),
	search_params: Schema.optionalKey(SearchParams),
})

export type ListScopesResponse = ReadonlyArray<
	{
		readonly tenantId: string
		readonly id: string
		readonly resourceId: string
		readonly name: string
		readonly description: string | null
		readonly createdAt: number
	} & { readonly [x: string]: Schema.Json }
>
export const ListScopesResponse = Schema.Array(
	Schema.StructWithRest(
		Schema.Struct({
			tenantId: Schema.String.check(Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })),
			id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
				Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
			),
			resourceId: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
				Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
			),
			name: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
				Schema.isMaxCodePoints(256).annotate({ expected: 'a string with at most 256 code points' })
			),
			description: Schema.Union([Schema.String, Schema.Null]),
			createdAt: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
		}),
		[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
	)
)

export type CreateScopePayload = { readonly name: string; readonly description?: string | null } & { readonly [x: string]: Schema.Json }
export const CreateScopePayload = Schema.StructWithRest(
	Schema.Struct({
		name: Schema.String.annotate({ description: 'The name of the scope. It should be unique for the resource.' })
			.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' }))
			.check(Schema.isMaxCodePoints(256).annotate({ expected: 'a string with at most 256 code points' })),
		description: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
	}),
	[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
)

export type CreateScopeResponse = {
	readonly tenantId: string
	readonly id: string
	readonly resourceId: string
	readonly name: string
	readonly description: string | null
	readonly createdAt: number
} & { readonly [x: string]: Schema.Json }
export const CreateScopeResponse = Schema.StructWithRest(
	Schema.Struct({
		tenantId: Schema.String.check(Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })),
		id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
		),
		resourceId: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
		),
		name: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxCodePoints(256).annotate({ expected: 'a string with at most 256 code points' })
		),
		description: Schema.Union([Schema.String, Schema.Null]),
		createdAt: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
	}),
	[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
)

export type UpdateScopePayload = { readonly name?: string; readonly description?: string | null } & { readonly [x: string]: Schema.Json }
export const UpdateScopePayload = Schema.StructWithRest(
	Schema.Struct({
		name: Schema.optionalKey(
			Schema.String.annotate({ description: 'The updated name of the scope. It should be unique for the resource.' })
				.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' }))
				.check(Schema.isMaxCodePoints(256).annotate({ expected: 'a string with at most 256 code points' }))
		),
		description: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
	}),
	[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
)

export type UpdateScopeResponse = {
	readonly tenantId: string
	readonly id: string
	readonly resourceId: string
	readonly name: string
	readonly description: string | null
	readonly createdAt: number
} & { readonly [x: string]: Schema.Json }
export const UpdateScopeResponse = Schema.StructWithRest(
	Schema.Struct({
		tenantId: Schema.String.check(Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })),
		id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
		),
		resourceId: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxCodePoints(21).annotate({ expected: 'a string with at most 21 code points' })
		),
		name: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
			Schema.isMaxCodePoints(256).annotate({ expected: 'a string with at most 256 code points' })
		),
		description: Schema.Union([Schema.String, Schema.Null]),
		createdAt: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
	}),
	[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
)
