/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Schema from 'effect/Schema'

export type GetSamlAuthnParams = {
	readonly SAMLRequest: string
	readonly Signature?: string
	readonly SigAlg?: string
	readonly RelayState?: string | null
}
export const GetSamlAuthnParams = Schema.Struct({
	SAMLRequest: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })),
	Signature: Schema.optionalKey(Schema.String),
	SigAlg: Schema.optionalKey(Schema.String),
	RelayState: Schema.optionalKey(
		Schema.Union([
			Schema.String.check(Schema.isMaxLength(512).annotate({ expected: 'a value with a length of at most 512' })),
			Schema.Null,
		])
	),
})

export type CreateSamlAuthnFormUrlEncoded = { readonly SAMLRequest: string; readonly RelayState?: string }
export const CreateSamlAuthnFormUrlEncoded = Schema.Struct({
	SAMLRequest: Schema.String.annotate({ description: 'Base64-encoded SAML request message.' }),
	RelayState: Schema.optionalKey(Schema.String.annotate({ description: 'Optional state parameter to be returned in the response.' })),
})
