/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Schema from 'effect/Schema'

export type ApplicationLegacySecret = string
export const ApplicationLegacySecret = Schema.String.annotate({
	description:
		'The legacy client secret. This field is omitted after the legacy secret has been replaced by an internal secret. Retrieve current application secrets from the `/api/applications/{id}/secrets` endpoints.',
	identifier: 'ApplicationLegacySecret',
})

export type CreateSamlAuthnRequestJson = { readonly SAMLRequest: string; readonly RelayState?: string | null }
export const CreateSamlAuthnRequestJson = Schema.Struct({
	SAMLRequest: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })),
	RelayState: Schema.optionalKey(
		Schema.Union([
			Schema.String.check(Schema.isMaxLength(512).annotate({ expected: 'a value with a length of at most 512' })),
			Schema.Null,
		])
	),
})
