/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Schema from 'effect/Schema'

export type GetResponse = {
	readonly tenantId: string
	readonly id: string
	readonly color: { readonly primaryColor: string; readonly isDarkModeEnabled: boolean; readonly darkPrimaryColor: string }
	readonly branding: {
		readonly logoUrl?: string
		readonly darkLogoUrl?: string
		readonly favicon?: string
		readonly darkFavicon?: string
	}
	readonly hideLogtoBranding: boolean
	readonly languageInfo: {
		readonly autoDetect: boolean
		readonly fallbackLanguage:
			| 'af-ZA'
			| 'am-ET'
			| 'ar'
			| 'ar-AR'
			| 'as-IN'
			| 'az-AZ'
			| 'be-BY'
			| 'bg-BG'
			| 'bn-IN'
			| 'br-FR'
			| 'bs-BA'
			| 'ca-ES'
			| 'cb-IQ'
			| 'co-FR'
			| 'cs'
			| 'cs-CZ'
			| 'cx-PH'
			| 'cy-GB'
			| 'da-DK'
			| 'de'
			| 'de-DE'
			| 'el-GR'
			| 'en'
			| 'en-GB'
			| 'en-US'
			| 'eo-EO'
			| 'es'
			| 'es-ES'
			| 'es-419'
			| 'es-MX'
			| 'et-EE'
			| 'eu-ES'
			| 'fa-IR'
			| 'ff-NG'
			| 'fi'
			| 'fi-FI'
			| 'fo-FO'
			| 'fr'
			| 'fr-CA'
			| 'fr-FR'
			| 'fy-NL'
			| 'ga-IE'
			| 'gl-ES'
			| 'gn-PY'
			| 'gu-IN'
			| 'ha-NG'
			| 'he-IL'
			| 'hi-IN'
			| 'hr-HR'
			| 'ht-HT'
			| 'hu-HU'
			| 'hy-AM'
			| 'id-ID'
			| 'ik-US'
			| 'is-IS'
			| 'it'
			| 'it-IT'
			| 'iu-CA'
			| 'ja'
			| 'ja-JP'
			| 'ja-KS'
			| 'jv-ID'
			| 'ka-GE'
			| 'kk-KZ'
			| 'km-KH'
			| 'kn-IN'
			| 'ko'
			| 'ko-KR'
			| 'ku-TR'
			| 'ky-KG'
			| 'lo-LA'
			| 'lt-LT'
			| 'lv-LV'
			| 'mg-MG'
			| 'mk-MK'
			| 'ml-IN'
			| 'mn-MN'
			| 'mr-IN'
			| 'ms-MY'
			| 'mt-MT'
			| 'my-MM'
			| 'nb-NO'
			| 'ne-NP'
			| 'nl'
			| 'nl-BE'
			| 'nl-NL'
			| 'nn-NO'
			| 'or-IN'
			| 'pa-IN'
			| 'pl-PL'
			| 'ps-AF'
			| 'pt'
			| 'pt-BR'
			| 'pt-PT'
			| 'ro-RO'
			| 'ru'
			| 'ru-RU'
			| 'rw-RW'
			| 'sc-IT'
			| 'si-LK'
			| 'sk-SK'
			| 'sl-SI'
			| 'sn-ZW'
			| 'sq-AL'
			| 'sr-RS'
			| 'sv'
			| 'sv-SE'
			| 'sw-KE'
			| 'sy-SY'
			| 'sz-PL'
			| 'ta-IN'
			| 'te-IN'
			| 'tg-TJ'
			| 'th'
			| 'th-TH'
			| 'tl-PH'
			| 'tr'
			| 'tr-TR'
			| 'tt-RU'
			| 'tz-MA'
			| 'uk-UA'
			| 'ur-PK'
			| 'uz-UZ'
			| 'vi-VN'
			| 'zh'
			| 'zh-CN'
			| 'zh-HK'
			| 'zh-MO'
			| 'zh-TW'
			| 'zz-TR'
	}
	readonly termsOfUseUrl: string | null
	readonly privacyPolicyUrl: string | null
	readonly agreeToTermsPolicy: 'Automatic' | 'ManualRegistrationOnly' | 'Manual'
	readonly signIn: {
		readonly methods: ReadonlyArray<{
			readonly identifier: 'username' | 'email' | 'phone'
			readonly password: boolean
			readonly verificationCode: boolean
			readonly isPasswordPrimary: boolean
		}>
	}
	readonly signUp: {
		readonly identifiers: ReadonlyArray<'username' | 'email' | 'phone'>
		readonly password: boolean
		readonly verify: boolean
		readonly secondaryIdentifiers?: ReadonlyArray<{
			readonly identifier: 'username' | 'email' | 'phone' | 'emailOrPhone'
			readonly verify?: boolean
		}>
	}
	readonly socialSignIn: { readonly automaticAccountLinking?: boolean; readonly skipRequiredIdentifiers?: boolean }
	readonly socialSignInConnectorTargets: ReadonlyArray<string>
	readonly signInMode: 'SignIn' | 'Register' | 'SignInAndRegister'
	readonly customCss: string | null
	readonly customContent: { readonly [x: string]: string }
	readonly customUiAssets: ({ readonly id: string; readonly createdAt: number } & { readonly [x: string]: Schema.Json }) | null
	readonly customUiCsp: { readonly scriptSrc?: ReadonlyArray<string>; readonly connectSrc?: ReadonlyArray<string> }
	readonly passwordPolicy: {
		readonly length?: { readonly min: number; readonly max: number }
		readonly characterTypes?: { readonly min: number }
		readonly rejects?: {
			readonly pwned: boolean
			readonly repetitionAndSequence: boolean
			readonly userInfo: boolean
			readonly words: ReadonlyArray<string>
		}
	}
	readonly mfa: {
		readonly factors: ReadonlyArray<'Totp' | 'WebAuthn' | 'BackupCode' | 'EmailVerificationCode' | 'PhoneVerificationCode'>
		readonly policy:
			| 'UserControlled'
			| 'Mandatory'
			| 'PromptOnlyAtSignIn'
			| 'PromptAtSignInAndSignUp'
			| 'NoPrompt'
			| 'PromptAtSignInAndSignUpMandatory'
			| 'PromptOnlyAtSignInMandatory'
		readonly organizationRequiredMfaPolicy?: 'NoPrompt' | 'Mandatory'
	}
	readonly adaptiveMfa: { readonly enabled?: boolean }
	readonly singleSignOnEnabled: boolean
	readonly supportEmail: string | null
	readonly supportWebsiteUrl: string | null
	readonly unknownSessionRedirectUrl: string | null
	readonly captchaPolicy: { readonly enabled?: boolean }
	readonly sentinelPolicy: { readonly maxAttempts?: number; readonly lockoutDuration?: number }
	readonly emailBlocklistPolicy: {
		readonly blockDisposableAddresses?: boolean
		readonly blockSubaddressing?: boolean
		readonly customAllowlist?: ReadonlyArray<string>
		readonly customBlocklist?: ReadonlyArray<string>
	}
	readonly verificationCodePolicy: { readonly expirationDuration?: number; readonly maxRetryAttempts?: number }
	readonly forgotPasswordMethods: ReadonlyArray<'EmailVerificationCode' | 'PhoneVerificationCode'> | null
	readonly passkeySignIn: { readonly enabled?: boolean; readonly showPasskeyButton?: boolean; readonly allowAutofill?: boolean }
	readonly signUpProfileFields: ReadonlyArray<{ readonly name: string }> | null
	readonly passwordExpiration:
		| { readonly enabled?: boolean }
		| { readonly enabled: boolean; readonly validPeriodDays: number; readonly enabledAt?: number }
	readonly usernamePolicy: { readonly [x: string]: Schema.Json }
}
export const GetResponse = Schema.Struct({
	tenantId: Schema.String.check(Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })),
	id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
		Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })
	),
	color: Schema.Struct({
		primaryColor: Schema.String.annotate({ format: 'regex' }).check(
			Schema.isPattern(/^#[\da-fA-F]{3}([\da-fA-F]{3})?$/).annotate({
				expected: 'a string matching the RegExp ^#[\\da-fA-F]{3}([\\da-fA-F]{3})?$',
			})
		),
		isDarkModeEnabled: Schema.Boolean,
		darkPrimaryColor: Schema.String.annotate({ format: 'regex' }).check(
			Schema.isPattern(/^#[\da-fA-F]{3}([\da-fA-F]{3})?$/).annotate({
				expected: 'a string matching the RegExp ^#[\\da-fA-F]{3}([\\da-fA-F]{3})?$',
			})
		),
	}).annotate({ description: 'The primary branding color for the sign-in page (both light/dark mode).' }),
	branding: Schema.Struct({
		logoUrl: Schema.optionalKey(Schema.String.annotate({ format: 'url' })),
		darkLogoUrl: Schema.optionalKey(Schema.String.annotate({ format: 'url' })),
		favicon: Schema.optionalKey(Schema.String.annotate({ format: 'url' })),
		darkFavicon: Schema.optionalKey(Schema.String.annotate({ format: 'url' })),
	}),
	hideLogtoBranding: Schema.Boolean.annotate({ description: 'Cloud only. Whether to hide the Logto branding on hosted sign-in pages.' }),
	languageInfo: Schema.Struct({
		autoDetect: Schema.Boolean,
		fallbackLanguage: Schema.Literals([
			'af-ZA',
			'am-ET',
			'ar',
			'ar-AR',
			'as-IN',
			'az-AZ',
			'be-BY',
			'bg-BG',
			'bn-IN',
			'br-FR',
			'bs-BA',
			'ca-ES',
			'cb-IQ',
			'co-FR',
			'cs',
			'cs-CZ',
			'cx-PH',
			'cy-GB',
			'da-DK',
			'de',
			'de-DE',
			'el-GR',
			'en',
			'en-GB',
			'en-US',
			'eo-EO',
			'es',
			'es-ES',
			'es-419',
			'es-MX',
			'et-EE',
			'eu-ES',
			'fa-IR',
			'ff-NG',
			'fi',
			'fi-FI',
			'fo-FO',
			'fr',
			'fr-CA',
			'fr-FR',
			'fy-NL',
			'ga-IE',
			'gl-ES',
			'gn-PY',
			'gu-IN',
			'ha-NG',
			'he-IL',
			'hi-IN',
			'hr-HR',
			'ht-HT',
			'hu-HU',
			'hy-AM',
			'id-ID',
			'ik-US',
			'is-IS',
			'it',
			'it-IT',
			'iu-CA',
			'ja',
			'ja-JP',
			'ja-KS',
			'jv-ID',
			'ka-GE',
			'kk-KZ',
			'km-KH',
			'kn-IN',
			'ko',
			'ko-KR',
			'ku-TR',
			'ky-KG',
			'lo-LA',
			'lt-LT',
			'lv-LV',
			'mg-MG',
			'mk-MK',
			'ml-IN',
			'mn-MN',
			'mr-IN',
			'ms-MY',
			'mt-MT',
			'my-MM',
			'nb-NO',
			'ne-NP',
			'nl',
			'nl-BE',
			'nl-NL',
			'nn-NO',
			'or-IN',
			'pa-IN',
			'pl-PL',
			'ps-AF',
			'pt',
			'pt-BR',
			'pt-PT',
			'ro-RO',
			'ru',
			'ru-RU',
			'rw-RW',
			'sc-IT',
			'si-LK',
			'sk-SK',
			'sl-SI',
			'sn-ZW',
			'sq-AL',
			'sr-RS',
			'sv',
			'sv-SE',
			'sw-KE',
			'sy-SY',
			'sz-PL',
			'ta-IN',
			'te-IN',
			'tg-TJ',
			'th',
			'th-TH',
			'tl-PH',
			'tr',
			'tr-TR',
			'tt-RU',
			'tz-MA',
			'uk-UA',
			'ur-PK',
			'uz-UZ',
			'vi-VN',
			'zh',
			'zh-CN',
			'zh-HK',
			'zh-MO',
			'zh-TW',
			'zz-TR',
		]),
	}).annotate({ description: 'The language detection policy for the sign-in page.' }),
	termsOfUseUrl: Schema.Union([
		Schema.String.check(Schema.isMaxLength(2048).annotate({ expected: 'a value with a length of at most 2048' })),
		Schema.Null,
	]),
	privacyPolicyUrl: Schema.Union([
		Schema.String.check(Schema.isMaxLength(2048).annotate({ expected: 'a value with a length of at most 2048' })),
		Schema.Null,
	]),
	agreeToTermsPolicy: Schema.Literals(['Automatic', 'ManualRegistrationOnly', 'Manual']),
	signIn: Schema.Struct({
		methods: Schema.Array(
			Schema.Struct({
				identifier: Schema.Literals(['username', 'email', 'phone']),
				password: Schema.Boolean,
				verificationCode: Schema.Boolean,
				isPasswordPrimary: Schema.Boolean,
			})
		),
	}).annotate({ description: 'Sign-in method settings.' }),
	signUp: Schema.Struct({
		identifiers: Schema.Array(Schema.Literals(['username', 'email', 'phone'])).annotate({
			description: 'Allowed identifiers when signing-up.',
		}),
		password: Schema.Boolean.annotate({ description: 'Whether the user is required to set a password when signing-up.' }),
		verify: Schema.Boolean.annotate({ description: 'Whether the user is required to verify their email/phone when signing-up.' }),
		secondaryIdentifiers: Schema.optionalKey(
			Schema.Array(
				Schema.Struct({
					identifier: Schema.Union([Schema.Literals(['username', 'email', 'phone']), Schema.Literal('emailOrPhone')], {
						mode: 'oneOf',
					}),
					verify: Schema.optionalKey(Schema.Boolean),
				})
			).annotate({
				description:
					'Additional identifiers required during sign-up. Once specified, users will be prompted to provide these identifiers when creating an account.',
			})
		),
	}).annotate({ description: 'Sign-up method settings.' }),
	socialSignIn: Schema.Struct({
		automaticAccountLinking: Schema.optionalKey(Schema.Boolean),
		skipRequiredIdentifiers: Schema.optionalKey(Schema.Boolean),
	}),
	socialSignInConnectorTargets: Schema.Array(Schema.String).annotate({
		description: 'Enabled social sign-in connectors, will displayed on the sign-in page.',
	}),
	signInMode: Schema.Literals(['SignIn', 'Register', 'SignInAndRegister']),
	customCss: Schema.Union([Schema.String, Schema.Null]),
	customContent: Schema.Record(Schema.String, Schema.String).annotate({
		description:
			'Custom content to display on experience flow pages. the page pathname will be the config key, the content will be the config value.',
	}),
	customUiAssets: Schema.Union([
		Schema.StructWithRest(
			Schema.Struct({
				id: Schema.String,
				createdAt: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
			}),
			[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
		),
		Schema.Null,
	]),
	customUiCsp: Schema.Struct({
		scriptSrc: Schema.optionalKey(
			Schema.Array(Schema.String).annotate({
				description:
					'Additional source expressions appended to the `script-src` directive for scripts loaded by Custom UI assets. HTTPS sources are supported. HTTP localhost sources are allowed only outside production.',
			})
		),
		connectSrc: Schema.optionalKey(
			Schema.Array(Schema.String).annotate({
				description:
					'Additional source expressions appended to the `connect-src` directive for network requests made by Custom UI assets. HTTPS and WSS sources are supported. HTTP localhost sources are allowed only outside production.',
			})
		),
	}).annotate({
		description:
			'Cloud only. Additional Content Security Policy source expressions for Custom UI assets. These values are applied to the hosted sign-in page only when Custom UI assets are configured.',
	}),
	passwordPolicy: Schema.Struct({
		length: Schema.optionalKey(
			Schema.Struct({
				min: Schema.Number.annotate({ default: 8 }).check(Schema.isFinite().annotate({ expected: 'a finite number' })),
				max: Schema.Number.annotate({ default: 256 }).check(Schema.isFinite().annotate({ expected: 'a finite number' })),
			})
		),
		characterTypes: Schema.optionalKey(
			Schema.Struct({
				min: Schema.Number.annotate({ default: 1 }).check(Schema.isFinite().annotate({ expected: 'a finite number' })),
			})
		),
		rejects: Schema.optionalKey(
			Schema.Struct({
				pwned: Schema.Boolean.annotate({ default: true }),
				repetitionAndSequence: Schema.Boolean.annotate({ default: true }),
				userInfo: Schema.Boolean.annotate({ default: true }),
				words: Schema.Array(Schema.String).annotate({ default: [] }),
			})
		),
	}).annotate({ description: 'Password policies to adjust the password strength requirements.' }),
	mfa: Schema.Struct({
		factors: Schema.Array(Schema.Literals(['Totp', 'WebAuthn', 'BackupCode', 'EmailVerificationCode', 'PhoneVerificationCode'])),
		policy: Schema.Literals([
			'UserControlled',
			'Mandatory',
			'PromptOnlyAtSignIn',
			'PromptAtSignInAndSignUp',
			'NoPrompt',
			'PromptAtSignInAndSignUpMandatory',
			'PromptOnlyAtSignInMandatory',
		]),
		organizationRequiredMfaPolicy: Schema.optionalKey(Schema.Literals(['NoPrompt', 'Mandatory'])),
	}).annotate({ description: 'MFA settings' }),
	adaptiveMfa: Schema.Struct({ enabled: Schema.optionalKey(Schema.Boolean) }).annotate({ description: 'Adaptive MFA settings.' }),
	singleSignOnEnabled: Schema.Boolean,
	supportEmail: Schema.Union([Schema.String, Schema.Null]).annotate({
		description: 'The support email address to display on the error pages.',
	}),
	supportWebsiteUrl: Schema.Union([Schema.String, Schema.Null]).annotate({
		description: 'The support website URL to display on the error pages.',
	}),
	unknownSessionRedirectUrl: Schema.Union([Schema.String, Schema.Null]).annotate({
		description:
			'The fallback URL to redirect users when the sign-in session does not exist or unknown. Client should initiates a new authentication flow after the redirection.',
	}),
	captchaPolicy: Schema.Struct({ enabled: Schema.optionalKey(Schema.Boolean) }),
	sentinelPolicy: Schema.Struct({
		maxAttempts: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
		lockoutDuration: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
	}).annotate({
		description:
			'Custom sentinel policy settings. Use this field to customize the user lockout policy. The default value is 100 failed attempts within one hour. The user will be locked out for 60 minutes after exceeding the limit.',
	}),
	emailBlocklistPolicy: Schema.Struct({
		blockDisposableAddresses: Schema.optionalKey(
			Schema.Boolean.annotate({
				description:
					'Cloud only.  Whether to block disposable email addresses. Once enabled, Logto will check the email domain against a list of known disposable email domains. If the domain is found in the list, the email address will be blocked.',
			})
		),
		blockSubaddressing: Schema.optionalKey(
			Schema.Boolean.annotate({ description: 'Whether to block sub-addresses. (E.g., example+shopping@test.com)' })
		),
		customAllowlist: Schema.optionalKey(
			Schema.Array(Schema.String).annotate({
				description:
					'Custom allowlist of email addresses, domains, or wildcard email address patterns. Examples: `bar@example.com`, `@example.com`, `foo*@example.com`, `@*.example.com`.',
			})
		),
		customBlocklist: Schema.optionalKey(
			Schema.Array(Schema.String).annotate({
				description:
					'Custom blocklist of email addresses, domains, or wildcard email address patterns. Examples: `bar@example.com`, `@example.com`, `foo*@example.com`, `@*.example.com`.',
			})
		),
	}).annotate({ description: 'Define email restriction policies for registering or linking email addresses.' }),
	verificationCodePolicy: Schema.Struct({
		expirationDuration: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
		maxRetryAttempts: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
	}),
	forgotPasswordMethods: Schema.Union([Schema.Array(Schema.Literals(['EmailVerificationCode', 'PhoneVerificationCode'])), Schema.Null]),
	passkeySignIn: Schema.Struct({
		enabled: Schema.optionalKey(Schema.Boolean),
		showPasskeyButton: Schema.optionalKey(Schema.Boolean),
		allowAutofill: Schema.optionalKey(Schema.Boolean),
	}),
	signUpProfileFields: Schema.Union([Schema.Array(Schema.Struct({ name: Schema.String })), Schema.Null]),
	passwordExpiration: Schema.Union(
		[
			Schema.Struct({ enabled: Schema.optionalKey(Schema.Boolean.annotate({ format: 'false' })) }),
			Schema.Struct({
				enabled: Schema.Boolean.annotate({ format: 'true' }),
				validPeriodDays: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
				enabledAt: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
			}),
		],
		{ mode: 'oneOf' }
	).annotate({
		description:
			'Password expiration policy used to force users to reset their password during sign-in. When enabled is false, the period field is ignored.',
	}),
	usernamePolicy: Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' })).annotate({
		description: 'Validator function',
	}),
})

export type UpdateParams = { readonly removeUnusedDemoSocialConnector?: string }
export const UpdateParams = Schema.Struct({ removeUnusedDemoSocialConnector: Schema.optionalKey(Schema.String) })

export type UpdatePayload = {
	readonly tenantId?: string
	readonly color?: { readonly primaryColor: string; readonly isDarkModeEnabled: boolean; readonly darkPrimaryColor: string }
	readonly branding?: {
		readonly logoUrl?: string
		readonly darkLogoUrl?: string
		readonly favicon?: string
		readonly darkFavicon?: string
	}
	readonly hideLogtoBranding?: boolean
	readonly languageInfo?: {
		readonly autoDetect: boolean
		readonly fallbackLanguage:
			| 'af-ZA'
			| 'am-ET'
			| 'ar'
			| 'ar-AR'
			| 'as-IN'
			| 'az-AZ'
			| 'be-BY'
			| 'bg-BG'
			| 'bn-IN'
			| 'br-FR'
			| 'bs-BA'
			| 'ca-ES'
			| 'cb-IQ'
			| 'co-FR'
			| 'cs'
			| 'cs-CZ'
			| 'cx-PH'
			| 'cy-GB'
			| 'da-DK'
			| 'de'
			| 'de-DE'
			| 'el-GR'
			| 'en'
			| 'en-GB'
			| 'en-US'
			| 'eo-EO'
			| 'es'
			| 'es-ES'
			| 'es-419'
			| 'es-MX'
			| 'et-EE'
			| 'eu-ES'
			| 'fa-IR'
			| 'ff-NG'
			| 'fi'
			| 'fi-FI'
			| 'fo-FO'
			| 'fr'
			| 'fr-CA'
			| 'fr-FR'
			| 'fy-NL'
			| 'ga-IE'
			| 'gl-ES'
			| 'gn-PY'
			| 'gu-IN'
			| 'ha-NG'
			| 'he-IL'
			| 'hi-IN'
			| 'hr-HR'
			| 'ht-HT'
			| 'hu-HU'
			| 'hy-AM'
			| 'id-ID'
			| 'ik-US'
			| 'is-IS'
			| 'it'
			| 'it-IT'
			| 'iu-CA'
			| 'ja'
			| 'ja-JP'
			| 'ja-KS'
			| 'jv-ID'
			| 'ka-GE'
			| 'kk-KZ'
			| 'km-KH'
			| 'kn-IN'
			| 'ko'
			| 'ko-KR'
			| 'ku-TR'
			| 'ky-KG'
			| 'lo-LA'
			| 'lt-LT'
			| 'lv-LV'
			| 'mg-MG'
			| 'mk-MK'
			| 'ml-IN'
			| 'mn-MN'
			| 'mr-IN'
			| 'ms-MY'
			| 'mt-MT'
			| 'my-MM'
			| 'nb-NO'
			| 'ne-NP'
			| 'nl'
			| 'nl-BE'
			| 'nl-NL'
			| 'nn-NO'
			| 'or-IN'
			| 'pa-IN'
			| 'pl-PL'
			| 'ps-AF'
			| 'pt'
			| 'pt-BR'
			| 'pt-PT'
			| 'ro-RO'
			| 'ru'
			| 'ru-RU'
			| 'rw-RW'
			| 'sc-IT'
			| 'si-LK'
			| 'sk-SK'
			| 'sl-SI'
			| 'sn-ZW'
			| 'sq-AL'
			| 'sr-RS'
			| 'sv'
			| 'sv-SE'
			| 'sw-KE'
			| 'sy-SY'
			| 'sz-PL'
			| 'ta-IN'
			| 'te-IN'
			| 'tg-TJ'
			| 'th'
			| 'th-TH'
			| 'tl-PH'
			| 'tr'
			| 'tr-TR'
			| 'tt-RU'
			| 'tz-MA'
			| 'uk-UA'
			| 'ur-PK'
			| 'uz-UZ'
			| 'vi-VN'
			| 'zh'
			| 'zh-CN'
			| 'zh-HK'
			| 'zh-MO'
			| 'zh-TW'
			| 'zz-TR'
	}
	readonly agreeToTermsPolicy?: 'Automatic' | 'ManualRegistrationOnly' | 'Manual'
	readonly signIn?: {
		readonly methods: ReadonlyArray<{
			readonly identifier: 'username' | 'email' | 'phone'
			readonly password: boolean
			readonly verificationCode: boolean
			readonly isPasswordPrimary: boolean
		}>
	}
	readonly signUp?: {
		readonly identifiers: ReadonlyArray<'username' | 'email' | 'phone'>
		readonly password: boolean
		readonly verify: boolean
		readonly secondaryIdentifiers?: ReadonlyArray<{
			readonly identifier: 'username' | 'email' | 'phone' | 'emailOrPhone'
			readonly verify?: boolean
		}>
	}
	readonly socialSignIn?: { readonly automaticAccountLinking?: boolean; readonly skipRequiredIdentifiers?: boolean }
	readonly socialSignInConnectorTargets?: ReadonlyArray<string>
	readonly signInMode?: 'SignIn' | 'Register' | 'SignInAndRegister'
	readonly customCss?: string | null
	readonly customContent?: { readonly [x: string]: string }
	readonly customUiAssets?: ({ readonly id: string; readonly createdAt: number } & { readonly [x: string]: Schema.Json }) | null
	readonly customUiCsp?: { readonly scriptSrc?: ReadonlyArray<string>; readonly connectSrc?: ReadonlyArray<string> }
	readonly passwordPolicy?: {
		readonly length?: { readonly min: number; readonly max: number }
		readonly characterTypes?: { readonly min: number }
		readonly rejects?: {
			readonly pwned: boolean
			readonly repetitionAndSequence: boolean
			readonly userInfo: boolean
			readonly words: ReadonlyArray<string>
		}
	}
	readonly mfa?: {
		readonly factors: ReadonlyArray<'Totp' | 'WebAuthn' | 'BackupCode' | 'EmailVerificationCode' | 'PhoneVerificationCode'>
		readonly policy:
			| 'UserControlled'
			| 'Mandatory'
			| 'PromptOnlyAtSignIn'
			| 'PromptAtSignInAndSignUp'
			| 'NoPrompt'
			| 'PromptAtSignInAndSignUpMandatory'
			| 'PromptOnlyAtSignInMandatory'
		readonly organizationRequiredMfaPolicy?: 'NoPrompt' | 'Mandatory'
	}
	readonly adaptiveMfa?: { readonly enabled?: boolean }
	readonly singleSignOnEnabled?: boolean
	readonly captchaPolicy?: { readonly enabled?: boolean }
	readonly sentinelPolicy?: { readonly maxAttempts?: number; readonly lockoutDuration?: number }
	readonly emailBlocklistPolicy?: {
		readonly blockDisposableAddresses?: boolean
		readonly blockSubaddressing?: boolean
		readonly customAllowlist?: ReadonlyArray<string>
		readonly customBlocklist?: ReadonlyArray<string>
	}
	readonly forgotPasswordMethods?: ReadonlyArray<'EmailVerificationCode' | 'PhoneVerificationCode'> | null
	readonly passkeySignIn?: { readonly enabled?: boolean; readonly showPasskeyButton?: boolean; readonly allowAutofill?: boolean }
	readonly signUpProfileFields?: ReadonlyArray<{ readonly name: string }> | null
	readonly usernamePolicy?: { readonly [x: string]: Schema.Json }
	readonly termsOfUseUrl?: string | null | string
	readonly privacyPolicyUrl?: string | null | string
	readonly supportEmail?: string | null | string
	readonly supportWebsiteUrl?: string | null | string
	readonly unknownSessionRedirectUrl?: string | null | string
	readonly passwordExpiration?:
		| { readonly enabled?: boolean }
		| { readonly enabled: boolean; readonly validPeriodDays: number; readonly enabledAt?: number }
	readonly verificationCodePolicy?: { readonly expirationDuration?: number; readonly maxRetryAttempts?: number }
}
export const UpdatePayload = Schema.Struct({
	tenantId: Schema.optionalKey(Schema.String.check(Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' }))),
	color: Schema.optionalKey(
		Schema.Struct({
			primaryColor: Schema.String.annotate({ format: 'regex' }).check(
				Schema.isPattern(/^#[\da-fA-F]{3}([\da-fA-F]{3})?$/).annotate({
					expected: 'a string matching the RegExp ^#[\\da-fA-F]{3}([\\da-fA-F]{3})?$',
				})
			),
			isDarkModeEnabled: Schema.Boolean,
			darkPrimaryColor: Schema.String.annotate({ format: 'regex' }).check(
				Schema.isPattern(/^#[\da-fA-F]{3}([\da-fA-F]{3})?$/).annotate({
					expected: 'a string matching the RegExp ^#[\\da-fA-F]{3}([\\da-fA-F]{3})?$',
				})
			),
		}).annotate({ description: 'Specify the primary branding color for the sign-in page (both light/dark mode).' })
	),
	branding: Schema.optionalKey(
		Schema.Struct({
			logoUrl: Schema.optionalKey(Schema.String.annotate({ format: 'url' })),
			darkLogoUrl: Schema.optionalKey(Schema.String.annotate({ format: 'url' })),
			favicon: Schema.optionalKey(Schema.String.annotate({ format: 'url' })),
			darkFavicon: Schema.optionalKey(Schema.String.annotate({ format: 'url' })),
		})
	),
	hideLogtoBranding: Schema.optionalKey(
		Schema.Boolean.annotate({ description: 'Cloud only. Whether to hide the Logto branding on hosted sign-in pages.' })
	),
	languageInfo: Schema.optionalKey(
		Schema.Struct({
			autoDetect: Schema.Boolean,
			fallbackLanguage: Schema.Literals([
				'af-ZA',
				'am-ET',
				'ar',
				'ar-AR',
				'as-IN',
				'az-AZ',
				'be-BY',
				'bg-BG',
				'bn-IN',
				'br-FR',
				'bs-BA',
				'ca-ES',
				'cb-IQ',
				'co-FR',
				'cs',
				'cs-CZ',
				'cx-PH',
				'cy-GB',
				'da-DK',
				'de',
				'de-DE',
				'el-GR',
				'en',
				'en-GB',
				'en-US',
				'eo-EO',
				'es',
				'es-ES',
				'es-419',
				'es-MX',
				'et-EE',
				'eu-ES',
				'fa-IR',
				'ff-NG',
				'fi',
				'fi-FI',
				'fo-FO',
				'fr',
				'fr-CA',
				'fr-FR',
				'fy-NL',
				'ga-IE',
				'gl-ES',
				'gn-PY',
				'gu-IN',
				'ha-NG',
				'he-IL',
				'hi-IN',
				'hr-HR',
				'ht-HT',
				'hu-HU',
				'hy-AM',
				'id-ID',
				'ik-US',
				'is-IS',
				'it',
				'it-IT',
				'iu-CA',
				'ja',
				'ja-JP',
				'ja-KS',
				'jv-ID',
				'ka-GE',
				'kk-KZ',
				'km-KH',
				'kn-IN',
				'ko',
				'ko-KR',
				'ku-TR',
				'ky-KG',
				'lo-LA',
				'lt-LT',
				'lv-LV',
				'mg-MG',
				'mk-MK',
				'ml-IN',
				'mn-MN',
				'mr-IN',
				'ms-MY',
				'mt-MT',
				'my-MM',
				'nb-NO',
				'ne-NP',
				'nl',
				'nl-BE',
				'nl-NL',
				'nn-NO',
				'or-IN',
				'pa-IN',
				'pl-PL',
				'ps-AF',
				'pt',
				'pt-BR',
				'pt-PT',
				'ro-RO',
				'ru',
				'ru-RU',
				'rw-RW',
				'sc-IT',
				'si-LK',
				'sk-SK',
				'sl-SI',
				'sn-ZW',
				'sq-AL',
				'sr-RS',
				'sv',
				'sv-SE',
				'sw-KE',
				'sy-SY',
				'sz-PL',
				'ta-IN',
				'te-IN',
				'tg-TJ',
				'th',
				'th-TH',
				'tl-PH',
				'tr',
				'tr-TR',
				'tt-RU',
				'tz-MA',
				'uk-UA',
				'ur-PK',
				'uz-UZ',
				'vi-VN',
				'zh',
				'zh-CN',
				'zh-HK',
				'zh-MO',
				'zh-TW',
				'zz-TR',
			]),
		}).annotate({ description: 'Control the language detection policy for the sign-in page.' })
	),
	agreeToTermsPolicy: Schema.optionalKey(Schema.Literals(['Automatic', 'ManualRegistrationOnly', 'Manual'])),
	signIn: Schema.optionalKey(
		Schema.Struct({
			methods: Schema.Array(
				Schema.Struct({
					identifier: Schema.Literals(['username', 'email', 'phone']),
					password: Schema.Boolean,
					verificationCode: Schema.Boolean,
					isPasswordPrimary: Schema.Boolean,
				})
			),
		}).annotate({ description: 'Sign-in method settings' })
	),
	signUp: Schema.optionalKey(
		Schema.Struct({
			identifiers: Schema.Array(Schema.Literals(['username', 'email', 'phone'])).annotate({
				description: 'Specify allowed identifiers when signing-up.',
			}),
			password: Schema.Boolean.annotate({ description: 'Whether the user is required to set a password when signing-up.' }),
			verify: Schema.Boolean.annotate({ description: 'Whether the user is required to verify their email/phone when signing-up.' }),
			secondaryIdentifiers: Schema.optionalKey(
				Schema.Array(
					Schema.Struct({
						identifier: Schema.Union([Schema.Literals(['username', 'email', 'phone']), Schema.Literal('emailOrPhone')], {
							mode: 'oneOf',
						}),
						verify: Schema.optionalKey(Schema.Boolean),
					})
				)
			),
		}).annotate({ description: 'Sign-up method settings' })
	),
	socialSignIn: Schema.optionalKey(
		Schema.Struct({
			automaticAccountLinking: Schema.optionalKey(Schema.Boolean),
			skipRequiredIdentifiers: Schema.optionalKey(Schema.Boolean),
		})
	),
	socialSignInConnectorTargets: Schema.optionalKey(
		Schema.Array(Schema.String).annotate({ description: 'Specify the social sign-in connectors to display on the sign-in page.' })
	),
	signInMode: Schema.optionalKey(Schema.Literals(['SignIn', 'Register', 'SignInAndRegister'])),
	customCss: Schema.optionalKey(Schema.Union([Schema.String, Schema.Null])),
	customContent: Schema.optionalKey(
		Schema.Record(Schema.String, Schema.String).annotate({
			description:
				'Custom content to display on experience flow pages. the page pathname will be the config key, the content will be the config value.',
		})
	),
	customUiAssets: Schema.optionalKey(
		Schema.Union([
			Schema.StructWithRest(
				Schema.Struct({
					id: Schema.String,
					createdAt: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
				}),
				[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
			),
			Schema.Null,
		])
	),
	customUiCsp: Schema.optionalKey(
		Schema.Struct({
			scriptSrc: Schema.optionalKey(
				Schema.Array(Schema.String).annotate({
					description:
						'Additional source expressions to append to the `script-src` directive for scripts loaded by Custom UI assets. Use HTTPS sources; HTTP localhost sources are allowed only outside production.',
				})
			),
			connectSrc: Schema.optionalKey(
				Schema.Array(Schema.String).annotate({
					description:
						'Additional source expressions to append to the `connect-src` directive for network requests made by Custom UI assets. Use HTTPS or WSS sources; HTTP localhost sources are allowed only outside production.',
				})
			),
		}).annotate({
			description:
				'Cloud only. Configure additional Content Security Policy source expressions for Custom UI assets. These values are applied to the hosted sign-in page only when Custom UI assets are configured.',
		})
	),
	passwordPolicy: Schema.optionalKey(
		Schema.Struct({
			length: Schema.optionalKey(
				Schema.Struct({
					min: Schema.Number.annotate({ default: 8 }).check(Schema.isFinite().annotate({ expected: 'a finite number' })),
					max: Schema.Number.annotate({ default: 256 }).check(Schema.isFinite().annotate({ expected: 'a finite number' })),
				})
			),
			characterTypes: Schema.optionalKey(
				Schema.Struct({
					min: Schema.Number.annotate({ default: 1 }).check(Schema.isFinite().annotate({ expected: 'a finite number' })),
				})
			),
			rejects: Schema.optionalKey(
				Schema.Struct({
					pwned: Schema.Boolean.annotate({ default: true }),
					repetitionAndSequence: Schema.Boolean.annotate({ default: true }),
					userInfo: Schema.Boolean.annotate({ default: true }),
					words: Schema.Array(Schema.String).annotate({ default: [] }),
				})
			),
		}).annotate({ description: 'Password policies to adjust the password strength requirements.' })
	),
	mfa: Schema.optionalKey(
		Schema.Struct({
			factors: Schema.Array(Schema.Literals(['Totp', 'WebAuthn', 'BackupCode', 'EmailVerificationCode', 'PhoneVerificationCode'])),
			policy: Schema.Literals([
				'UserControlled',
				'Mandatory',
				'PromptOnlyAtSignIn',
				'PromptAtSignInAndSignUp',
				'NoPrompt',
				'PromptAtSignInAndSignUpMandatory',
				'PromptOnlyAtSignInMandatory',
			]),
			organizationRequiredMfaPolicy: Schema.optionalKey(Schema.Literals(['NoPrompt', 'Mandatory'])),
		}).annotate({ description: 'MFA settings' })
	),
	adaptiveMfa: Schema.optionalKey(
		Schema.Struct({ enabled: Schema.optionalKey(Schema.Boolean) }).annotate({
			description: 'Adaptive MFA settings. Only effective when developer features are enabled.',
		})
	),
	singleSignOnEnabled: Schema.optionalKey(Schema.Boolean),
	captchaPolicy: Schema.optionalKey(Schema.Struct({ enabled: Schema.optionalKey(Schema.Boolean) })),
	sentinelPolicy: Schema.optionalKey(
		Schema.Struct({
			maxAttempts: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
			lockoutDuration: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
		}).annotate({
			description:
				'Custom sentinel policy settings. Use this field to customize the user lockout policy. The default value is 100 failed attempts within one hour. The user will be locked out for 60 minutes after exceeding the limit.',
		})
	),
	emailBlocklistPolicy: Schema.optionalKey(
		Schema.Struct({
			blockDisposableAddresses: Schema.optionalKey(
				Schema.Boolean.annotate({
					description:
						'Cloud only.  Whether to block disposable email addresses. Once enabled, Logto will check the email domain against a list of known disposable email domains. If the domain is found in the list, the email address will be blocked.',
				})
			),
			blockSubaddressing: Schema.optionalKey(
				Schema.Boolean.annotate({ description: 'Whether to block sub-addresses. (E.g., example+shopping@test.com)' })
			),
			customAllowlist: Schema.optionalKey(
				Schema.Array(Schema.String).annotate({
					description:
						'Custom allowlist of email addresses, domains, or wildcard email address patterns. Examples: `bar@example.com`, `@example.com`, `foo*@example.com`, `@*.example.com`.',
				})
			),
			customBlocklist: Schema.optionalKey(
				Schema.Array(Schema.String).annotate({
					description:
						'Custom blocklist of email addresses, domains, or wildcard email address patterns. Examples: `bar@example.com`, `@example.com`, `foo*@example.com`, `@*.example.com`.',
				})
			),
		}).annotate({ description: 'Define email restriction policies for registering or linking email addresses.' })
	),
	forgotPasswordMethods: Schema.optionalKey(
		Schema.Union([Schema.Array(Schema.Literals(['EmailVerificationCode', 'PhoneVerificationCode'])), Schema.Null])
	),
	passkeySignIn: Schema.optionalKey(
		Schema.Struct({
			enabled: Schema.optionalKey(Schema.Boolean),
			showPasskeyButton: Schema.optionalKey(Schema.Boolean),
			allowAutofill: Schema.optionalKey(Schema.Boolean),
		})
	),
	signUpProfileFields: Schema.optionalKey(Schema.Union([Schema.Array(Schema.Struct({ name: Schema.String })), Schema.Null])),
	usernamePolicy: Schema.optionalKey(
		Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' })).annotate({ description: 'Validator function' })
	),
	termsOfUseUrl: Schema.optionalKey(
		Schema.Union(
			[Schema.Union([Schema.String, Schema.Null]).annotate({ format: 'url' }), Schema.String.annotate({ format: 'empty' })],
			{ mode: 'oneOf' }
		)
	),
	privacyPolicyUrl: Schema.optionalKey(
		Schema.Union(
			[Schema.Union([Schema.String, Schema.Null]).annotate({ format: 'url' }), Schema.String.annotate({ format: 'empty' })],
			{ mode: 'oneOf' }
		)
	),
	supportEmail: Schema.optionalKey(
		Schema.Union(
			[Schema.Union([Schema.String, Schema.Null]).annotate({ format: 'email' }), Schema.String.annotate({ format: 'empty' })],
			{ mode: 'oneOf' }
		).annotate({ description: 'The support email address to display on the error pages.' })
	),
	supportWebsiteUrl: Schema.optionalKey(
		Schema.Union(
			[Schema.Union([Schema.String, Schema.Null]).annotate({ format: 'url' }), Schema.String.annotate({ format: 'empty' })],
			{ mode: 'oneOf' }
		).annotate({ description: 'The support website URL to display on the error pages.' })
	),
	unknownSessionRedirectUrl: Schema.optionalKey(
		Schema.Union(
			[Schema.Union([Schema.String, Schema.Null]).annotate({ format: 'url' }), Schema.String.annotate({ format: 'empty' })],
			{ mode: 'oneOf' }
		).annotate({
			description:
				'The fallback URL to redirect users when the sign-in session does not exist or unknown. Client should initiate a new authentication flow after the redirection.',
		})
	),
	passwordExpiration: Schema.optionalKey(
		Schema.Union(
			[
				Schema.Struct({ enabled: Schema.optionalKey(Schema.Boolean.annotate({ format: 'false' })) }),
				Schema.Struct({
					enabled: Schema.Boolean.annotate({ format: 'true' }),
					validPeriodDays: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
					enabledAt: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
				}),
			],
			{ mode: 'oneOf' }
		).annotate({
			description:
				'Password expiration policy used to force users to reset their password during sign-in. When enabled is false, the period field is ignored.',
		})
	),
	verificationCodePolicy: Schema.optionalKey(
		Schema.Struct({
			expirationDuration: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
			maxRetryAttempts: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
		})
	),
})

export type UpdateResponse = {
	readonly tenantId: string
	readonly id: string
	readonly color: { readonly primaryColor: string; readonly isDarkModeEnabled: boolean; readonly darkPrimaryColor: string }
	readonly branding: {
		readonly logoUrl?: string
		readonly darkLogoUrl?: string
		readonly favicon?: string
		readonly darkFavicon?: string
	}
	readonly hideLogtoBranding: boolean
	readonly languageInfo: {
		readonly autoDetect: boolean
		readonly fallbackLanguage:
			| 'af-ZA'
			| 'am-ET'
			| 'ar'
			| 'ar-AR'
			| 'as-IN'
			| 'az-AZ'
			| 'be-BY'
			| 'bg-BG'
			| 'bn-IN'
			| 'br-FR'
			| 'bs-BA'
			| 'ca-ES'
			| 'cb-IQ'
			| 'co-FR'
			| 'cs'
			| 'cs-CZ'
			| 'cx-PH'
			| 'cy-GB'
			| 'da-DK'
			| 'de'
			| 'de-DE'
			| 'el-GR'
			| 'en'
			| 'en-GB'
			| 'en-US'
			| 'eo-EO'
			| 'es'
			| 'es-ES'
			| 'es-419'
			| 'es-MX'
			| 'et-EE'
			| 'eu-ES'
			| 'fa-IR'
			| 'ff-NG'
			| 'fi'
			| 'fi-FI'
			| 'fo-FO'
			| 'fr'
			| 'fr-CA'
			| 'fr-FR'
			| 'fy-NL'
			| 'ga-IE'
			| 'gl-ES'
			| 'gn-PY'
			| 'gu-IN'
			| 'ha-NG'
			| 'he-IL'
			| 'hi-IN'
			| 'hr-HR'
			| 'ht-HT'
			| 'hu-HU'
			| 'hy-AM'
			| 'id-ID'
			| 'ik-US'
			| 'is-IS'
			| 'it'
			| 'it-IT'
			| 'iu-CA'
			| 'ja'
			| 'ja-JP'
			| 'ja-KS'
			| 'jv-ID'
			| 'ka-GE'
			| 'kk-KZ'
			| 'km-KH'
			| 'kn-IN'
			| 'ko'
			| 'ko-KR'
			| 'ku-TR'
			| 'ky-KG'
			| 'lo-LA'
			| 'lt-LT'
			| 'lv-LV'
			| 'mg-MG'
			| 'mk-MK'
			| 'ml-IN'
			| 'mn-MN'
			| 'mr-IN'
			| 'ms-MY'
			| 'mt-MT'
			| 'my-MM'
			| 'nb-NO'
			| 'ne-NP'
			| 'nl'
			| 'nl-BE'
			| 'nl-NL'
			| 'nn-NO'
			| 'or-IN'
			| 'pa-IN'
			| 'pl-PL'
			| 'ps-AF'
			| 'pt'
			| 'pt-BR'
			| 'pt-PT'
			| 'ro-RO'
			| 'ru'
			| 'ru-RU'
			| 'rw-RW'
			| 'sc-IT'
			| 'si-LK'
			| 'sk-SK'
			| 'sl-SI'
			| 'sn-ZW'
			| 'sq-AL'
			| 'sr-RS'
			| 'sv'
			| 'sv-SE'
			| 'sw-KE'
			| 'sy-SY'
			| 'sz-PL'
			| 'ta-IN'
			| 'te-IN'
			| 'tg-TJ'
			| 'th'
			| 'th-TH'
			| 'tl-PH'
			| 'tr'
			| 'tr-TR'
			| 'tt-RU'
			| 'tz-MA'
			| 'uk-UA'
			| 'ur-PK'
			| 'uz-UZ'
			| 'vi-VN'
			| 'zh'
			| 'zh-CN'
			| 'zh-HK'
			| 'zh-MO'
			| 'zh-TW'
			| 'zz-TR'
	}
	readonly termsOfUseUrl: string | null
	readonly privacyPolicyUrl: string | null
	readonly agreeToTermsPolicy: 'Automatic' | 'ManualRegistrationOnly' | 'Manual'
	readonly signIn: {
		readonly methods: ReadonlyArray<{
			readonly identifier: 'username' | 'email' | 'phone'
			readonly password: boolean
			readonly verificationCode: boolean
			readonly isPasswordPrimary: boolean
		}>
	}
	readonly signUp: {
		readonly identifiers: ReadonlyArray<'username' | 'email' | 'phone'>
		readonly password: boolean
		readonly verify: boolean
		readonly secondaryIdentifiers?: ReadonlyArray<{
			readonly identifier: 'username' | 'email' | 'phone' | 'emailOrPhone'
			readonly verify?: boolean
		}>
	}
	readonly socialSignIn: { readonly automaticAccountLinking?: boolean; readonly skipRequiredIdentifiers?: boolean }
	readonly socialSignInConnectorTargets: ReadonlyArray<string>
	readonly signInMode: 'SignIn' | 'Register' | 'SignInAndRegister'
	readonly customCss: string | null
	readonly customContent: { readonly [x: string]: string }
	readonly customUiAssets: ({ readonly id: string; readonly createdAt: number } & { readonly [x: string]: Schema.Json }) | null
	readonly customUiCsp: { readonly scriptSrc?: ReadonlyArray<string>; readonly connectSrc?: ReadonlyArray<string> }
	readonly passwordPolicy: {
		readonly length?: { readonly min: number; readonly max: number }
		readonly characterTypes?: { readonly min: number }
		readonly rejects?: {
			readonly pwned: boolean
			readonly repetitionAndSequence: boolean
			readonly userInfo: boolean
			readonly words: ReadonlyArray<string>
		}
	}
	readonly mfa: {
		readonly factors: ReadonlyArray<'Totp' | 'WebAuthn' | 'BackupCode' | 'EmailVerificationCode' | 'PhoneVerificationCode'>
		readonly policy:
			| 'UserControlled'
			| 'Mandatory'
			| 'PromptOnlyAtSignIn'
			| 'PromptAtSignInAndSignUp'
			| 'NoPrompt'
			| 'PromptAtSignInAndSignUpMandatory'
			| 'PromptOnlyAtSignInMandatory'
		readonly organizationRequiredMfaPolicy?: 'NoPrompt' | 'Mandatory'
	}
	readonly adaptiveMfa: { readonly enabled?: boolean }
	readonly singleSignOnEnabled: boolean
	readonly supportEmail: string | null
	readonly supportWebsiteUrl: string | null
	readonly unknownSessionRedirectUrl: string | null
	readonly captchaPolicy: { readonly enabled?: boolean }
	readonly sentinelPolicy: { readonly maxAttempts?: number; readonly lockoutDuration?: number }
	readonly emailBlocklistPolicy: {
		readonly blockDisposableAddresses?: boolean
		readonly blockSubaddressing?: boolean
		readonly customAllowlist?: ReadonlyArray<string>
		readonly customBlocklist?: ReadonlyArray<string>
	}
	readonly verificationCodePolicy: { readonly expirationDuration?: number; readonly maxRetryAttempts?: number }
	readonly forgotPasswordMethods: ReadonlyArray<'EmailVerificationCode' | 'PhoneVerificationCode'> | null
	readonly passkeySignIn: { readonly enabled?: boolean; readonly showPasskeyButton?: boolean; readonly allowAutofill?: boolean }
	readonly signUpProfileFields: ReadonlyArray<{ readonly name: string }> | null
	readonly passwordExpiration:
		| { readonly enabled?: boolean }
		| { readonly enabled: boolean; readonly validPeriodDays: number; readonly enabledAt?: number }
	readonly usernamePolicy: { readonly [x: string]: Schema.Json }
}
export const UpdateResponse = Schema.Struct({
	tenantId: Schema.String.check(Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })),
	id: Schema.String.check(Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })).check(
		Schema.isMaxLength(21).annotate({ expected: 'a value with a length of at most 21' })
	),
	color: Schema.Struct({
		primaryColor: Schema.String.annotate({ format: 'regex' }).check(
			Schema.isPattern(/^#[\da-fA-F]{3}([\da-fA-F]{3})?$/).annotate({
				expected: 'a string matching the RegExp ^#[\\da-fA-F]{3}([\\da-fA-F]{3})?$',
			})
		),
		isDarkModeEnabled: Schema.Boolean,
		darkPrimaryColor: Schema.String.annotate({ format: 'regex' }).check(
			Schema.isPattern(/^#[\da-fA-F]{3}([\da-fA-F]{3})?$/).annotate({
				expected: 'a string matching the RegExp ^#[\\da-fA-F]{3}([\\da-fA-F]{3})?$',
			})
		),
	}),
	branding: Schema.Struct({
		logoUrl: Schema.optionalKey(Schema.String.annotate({ format: 'url' })),
		darkLogoUrl: Schema.optionalKey(Schema.String.annotate({ format: 'url' })),
		favicon: Schema.optionalKey(Schema.String.annotate({ format: 'url' })),
		darkFavicon: Schema.optionalKey(Schema.String.annotate({ format: 'url' })),
	}),
	hideLogtoBranding: Schema.Boolean,
	languageInfo: Schema.Struct({
		autoDetect: Schema.Boolean,
		fallbackLanguage: Schema.Literals([
			'af-ZA',
			'am-ET',
			'ar',
			'ar-AR',
			'as-IN',
			'az-AZ',
			'be-BY',
			'bg-BG',
			'bn-IN',
			'br-FR',
			'bs-BA',
			'ca-ES',
			'cb-IQ',
			'co-FR',
			'cs',
			'cs-CZ',
			'cx-PH',
			'cy-GB',
			'da-DK',
			'de',
			'de-DE',
			'el-GR',
			'en',
			'en-GB',
			'en-US',
			'eo-EO',
			'es',
			'es-ES',
			'es-419',
			'es-MX',
			'et-EE',
			'eu-ES',
			'fa-IR',
			'ff-NG',
			'fi',
			'fi-FI',
			'fo-FO',
			'fr',
			'fr-CA',
			'fr-FR',
			'fy-NL',
			'ga-IE',
			'gl-ES',
			'gn-PY',
			'gu-IN',
			'ha-NG',
			'he-IL',
			'hi-IN',
			'hr-HR',
			'ht-HT',
			'hu-HU',
			'hy-AM',
			'id-ID',
			'ik-US',
			'is-IS',
			'it',
			'it-IT',
			'iu-CA',
			'ja',
			'ja-JP',
			'ja-KS',
			'jv-ID',
			'ka-GE',
			'kk-KZ',
			'km-KH',
			'kn-IN',
			'ko',
			'ko-KR',
			'ku-TR',
			'ky-KG',
			'lo-LA',
			'lt-LT',
			'lv-LV',
			'mg-MG',
			'mk-MK',
			'ml-IN',
			'mn-MN',
			'mr-IN',
			'ms-MY',
			'mt-MT',
			'my-MM',
			'nb-NO',
			'ne-NP',
			'nl',
			'nl-BE',
			'nl-NL',
			'nn-NO',
			'or-IN',
			'pa-IN',
			'pl-PL',
			'ps-AF',
			'pt',
			'pt-BR',
			'pt-PT',
			'ro-RO',
			'ru',
			'ru-RU',
			'rw-RW',
			'sc-IT',
			'si-LK',
			'sk-SK',
			'sl-SI',
			'sn-ZW',
			'sq-AL',
			'sr-RS',
			'sv',
			'sv-SE',
			'sw-KE',
			'sy-SY',
			'sz-PL',
			'ta-IN',
			'te-IN',
			'tg-TJ',
			'th',
			'th-TH',
			'tl-PH',
			'tr',
			'tr-TR',
			'tt-RU',
			'tz-MA',
			'uk-UA',
			'ur-PK',
			'uz-UZ',
			'vi-VN',
			'zh',
			'zh-CN',
			'zh-HK',
			'zh-MO',
			'zh-TW',
			'zz-TR',
		]),
	}),
	termsOfUseUrl: Schema.Union([
		Schema.String.check(Schema.isMaxLength(2048).annotate({ expected: 'a value with a length of at most 2048' })),
		Schema.Null,
	]),
	privacyPolicyUrl: Schema.Union([
		Schema.String.check(Schema.isMaxLength(2048).annotate({ expected: 'a value with a length of at most 2048' })),
		Schema.Null,
	]),
	agreeToTermsPolicy: Schema.Literals(['Automatic', 'ManualRegistrationOnly', 'Manual']),
	signIn: Schema.Struct({
		methods: Schema.Array(
			Schema.Struct({
				identifier: Schema.Literals(['username', 'email', 'phone']),
				password: Schema.Boolean,
				verificationCode: Schema.Boolean,
				isPasswordPrimary: Schema.Boolean,
			})
		),
	}),
	signUp: Schema.Struct({
		identifiers: Schema.Array(Schema.Literals(['username', 'email', 'phone'])),
		password: Schema.Boolean,
		verify: Schema.Boolean,
		secondaryIdentifiers: Schema.optionalKey(
			Schema.Array(
				Schema.Struct({
					identifier: Schema.Union([Schema.Literals(['username', 'email', 'phone']), Schema.Literal('emailOrPhone')], {
						mode: 'oneOf',
					}),
					verify: Schema.optionalKey(Schema.Boolean),
				})
			)
		),
	}),
	socialSignIn: Schema.Struct({
		automaticAccountLinking: Schema.optionalKey(Schema.Boolean),
		skipRequiredIdentifiers: Schema.optionalKey(Schema.Boolean),
	}),
	socialSignInConnectorTargets: Schema.Array(Schema.String),
	signInMode: Schema.Literals(['SignIn', 'Register', 'SignInAndRegister']),
	customCss: Schema.Union([Schema.String, Schema.Null]),
	customContent: Schema.Record(Schema.String, Schema.String),
	customUiAssets: Schema.Union([
		Schema.StructWithRest(
			Schema.Struct({
				id: Schema.String,
				createdAt: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
			}),
			[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
		),
		Schema.Null,
	]),
	customUiCsp: Schema.Struct({
		scriptSrc: Schema.optionalKey(Schema.Array(Schema.String)),
		connectSrc: Schema.optionalKey(Schema.Array(Schema.String)),
	}),
	passwordPolicy: Schema.Struct({
		length: Schema.optionalKey(
			Schema.Struct({
				min: Schema.Number.annotate({ default: 8 }).check(Schema.isFinite().annotate({ expected: 'a finite number' })),
				max: Schema.Number.annotate({ default: 256 }).check(Schema.isFinite().annotate({ expected: 'a finite number' })),
			})
		),
		characterTypes: Schema.optionalKey(
			Schema.Struct({
				min: Schema.Number.annotate({ default: 1 }).check(Schema.isFinite().annotate({ expected: 'a finite number' })),
			})
		),
		rejects: Schema.optionalKey(
			Schema.Struct({
				pwned: Schema.Boolean.annotate({ default: true }),
				repetitionAndSequence: Schema.Boolean.annotate({ default: true }),
				userInfo: Schema.Boolean.annotate({ default: true }),
				words: Schema.Array(Schema.String).annotate({ default: [] }),
			})
		),
	}),
	mfa: Schema.Struct({
		factors: Schema.Array(Schema.Literals(['Totp', 'WebAuthn', 'BackupCode', 'EmailVerificationCode', 'PhoneVerificationCode'])),
		policy: Schema.Literals([
			'UserControlled',
			'Mandatory',
			'PromptOnlyAtSignIn',
			'PromptAtSignInAndSignUp',
			'NoPrompt',
			'PromptAtSignInAndSignUpMandatory',
			'PromptOnlyAtSignInMandatory',
		]),
		organizationRequiredMfaPolicy: Schema.optionalKey(Schema.Literals(['NoPrompt', 'Mandatory'])),
	}),
	adaptiveMfa: Schema.Struct({ enabled: Schema.optionalKey(Schema.Boolean) }),
	singleSignOnEnabled: Schema.Boolean,
	supportEmail: Schema.Union([Schema.String, Schema.Null]),
	supportWebsiteUrl: Schema.Union([Schema.String, Schema.Null]),
	unknownSessionRedirectUrl: Schema.Union([Schema.String, Schema.Null]),
	captchaPolicy: Schema.Struct({ enabled: Schema.optionalKey(Schema.Boolean) }),
	sentinelPolicy: Schema.Struct({
		maxAttempts: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
		lockoutDuration: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
	}),
	emailBlocklistPolicy: Schema.Struct({
		blockDisposableAddresses: Schema.optionalKey(Schema.Boolean),
		blockSubaddressing: Schema.optionalKey(Schema.Boolean),
		customAllowlist: Schema.optionalKey(Schema.Array(Schema.String)),
		customBlocklist: Schema.optionalKey(Schema.Array(Schema.String)),
	}),
	verificationCodePolicy: Schema.Struct({
		expirationDuration: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
		maxRetryAttempts: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
	}),
	forgotPasswordMethods: Schema.Union([Schema.Array(Schema.Literals(['EmailVerificationCode', 'PhoneVerificationCode'])), Schema.Null]),
	passkeySignIn: Schema.Struct({
		enabled: Schema.optionalKey(Schema.Boolean),
		showPasskeyButton: Schema.optionalKey(Schema.Boolean),
		allowAutofill: Schema.optionalKey(Schema.Boolean),
	}),
	signUpProfileFields: Schema.Union([Schema.Array(Schema.Struct({ name: Schema.String })), Schema.Null]),
	passwordExpiration: Schema.Union(
		[
			Schema.Struct({ enabled: Schema.optionalKey(Schema.Boolean.annotate({ format: 'false' })) }),
			Schema.Struct({
				enabled: Schema.Boolean.annotate({ format: 'true' }),
				validPeriodDays: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
				enabledAt: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
			}),
		],
		{ mode: 'oneOf' }
	),
	usernamePolicy: Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' })).annotate({
		description: 'Validator function',
	}),
})

export type CheckPasswordWithDefaultSignInExperiencePayload = { readonly password: string; readonly userId?: string }
export const CheckPasswordWithDefaultSignInExperiencePayload = Schema.Struct({
	password: Schema.String.annotate({ description: 'The password to check.' }),
	userId: Schema.optionalKey(
		Schema.String.annotate({
			description: 'The user ID to check the password for. It is required if rejects user info is enabled in the password policy.',
		})
	),
})

export type CheckPasswordWithDefaultSignInExperienceResponse =
	| { readonly result: boolean }
	| {
			readonly result: boolean
			readonly issues: ReadonlyArray<{ readonly code: string; readonly interpolation?: { readonly [x: string]: Schema.Json } }>
	  }
export const CheckPasswordWithDefaultSignInExperienceResponse = Schema.Union(
	[
		Schema.Struct({ result: Schema.Boolean.annotate({ format: 'true' }) }),
		Schema.Struct({
			result: Schema.Boolean.annotate({ format: 'false' }),
			issues: Schema.Array(
				Schema.Struct({
					code: Schema.String,
					interpolation: Schema.optionalKey(
						Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value', examples: [{}] }))
					),
				})
			),
		}),
	],
	{ mode: 'oneOf' }
)

export type UploadCustomUiAssetsFormData =
	| null
	| string
	| number
	| boolean
	| ({ readonly file?: Schema.Json } & { readonly [x: string]: Schema.Json })
	| ReadonlyArray<Schema.Json>
export const UploadCustomUiAssetsFormData = Schema.Union([
	Schema.Null,
	Schema.String,
	Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
	Schema.Boolean,
	Schema.StructWithRest(
		Schema.Struct({
			file: Schema.optionalKey(
				Schema.Json.annotate({
					expected: 'JSON value',
					description: 'The zip file containing custom web assets such as HTML, CSS, and JavaScript files.',
				})
			),
		}),
		[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
	),
	Schema.Array(Schema.Json.annotate({ expected: 'JSON value' })),
])

export type UploadCustomUiAssetsResponse = { readonly customUiAssetId: string }
export const UploadCustomUiAssetsResponse = Schema.Struct({ customUiAssetId: Schema.String })

export type GetUsernameCaseSensitivityConflictsParams = { readonly limit: number }
export const GetUsernameCaseSensitivityConflictsParams = Schema.Struct({
	limit: Schema.Number.annotate({ default: 20 }).check(Schema.isFinite().annotate({ expected: 'a finite number' })),
})

export type GetUsernameCaseSensitivityConflictsResponse = {
	readonly totalConflicts: number
	readonly samples: ReadonlyArray<{ readonly usernameLower: string; readonly userIds: ReadonlyArray<string> }>
}
export const GetUsernameCaseSensitivityConflictsResponse = Schema.Struct({
	totalConflicts: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
	samples: Schema.Array(Schema.Struct({ usernameLower: Schema.String, userIds: Schema.Array(Schema.String) })),
})
