/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Schema from 'effect/Schema'

export type GetServiceStatusResponse = {
	readonly status: string | string
	readonly allowUploadMimeTypes?: ReadonlyArray<
		| 'image/jpeg'
		| 'image/png'
		| 'image/gif'
		| 'image/vnd.microsoft.icon'
		| 'image/x-icon'
		| 'image/svg+xml'
		| 'image/tiff'
		| 'image/webp'
		| 'image/bmp'
		| 'application/zip'
	>
	readonly maxUploadFileSize?: number
	readonly isExperienceAvatarUploadEnabled?: boolean
}
export const GetServiceStatusResponse = Schema.Struct({
	status: Schema.Union([Schema.String.annotate({ format: '"ready"' }), Schema.String.annotate({ format: '"not_configured"' })], {
		mode: 'oneOf',
	}),
	allowUploadMimeTypes: Schema.optionalKey(
		Schema.Array(
			Schema.Literals([
				'image/jpeg',
				'image/png',
				'image/gif',
				'image/vnd.microsoft.icon',
				'image/x-icon',
				'image/svg+xml',
				'image/tiff',
				'image/webp',
				'image/bmp',
				'application/zip',
			])
		)
	),
	maxUploadFileSize: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
	isExperienceAvatarUploadEnabled: Schema.optionalKey(Schema.Boolean),
})

export type CreateFormData =
	| null
	| string
	| number
	| boolean
	| ({ readonly file?: Schema.Json } & { readonly [x: string]: Schema.Json })
	| ReadonlyArray<Schema.Json>
export const CreateFormData = Schema.Union([
	Schema.Null,
	Schema.String,
	Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
	Schema.Boolean,
	Schema.StructWithRest(
		Schema.Struct({
			file: Schema.optionalKey(Schema.Json.annotate({ expected: 'JSON value', description: 'The file asset to upload.' })),
		}),
		[Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' }))]
	),
	Schema.Array(Schema.Json.annotate({ expected: 'JSON value' })),
])

export type CreateResponse = { readonly url: string }
export const CreateResponse = Schema.Struct({ url: Schema.String })
