/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Schema from 'effect/Schema'

export type CreateByPasswordPayload = { readonly password: string }
export const CreateByPasswordPayload = Schema.Struct({
	password: Schema.String.annotate({ description: 'The password of the user.' }).check(
		Schema.isMinLength(1).annotate({ expected: 'a value with a length of at least 1' })
	),
})

export type CreateByPasswordResponse = { readonly verificationRecordId: string; readonly expiresAt: string }
export const CreateByPasswordResponse = Schema.Struct({ verificationRecordId: Schema.String, expiresAt: Schema.String })

export type CreateByVerificationCodePayload = {
	readonly identifier: { readonly type: string; readonly value: string } | { readonly type: string; readonly value: string }
	readonly templateType?: string | string
}
export const CreateByVerificationCodePayload = Schema.Struct({
	identifier: Schema.Union(
		[
			Schema.Struct({
				type: Schema.String.annotate({ format: '"email"' }),
				value: Schema.String.annotate({ format: 'regex' })
					.check(Schema.isMaxLength(256).annotate({ expected: 'a value with a length of at most 256' }))
					.check(Schema.isPattern(/^\S+@\S+\.\S+$/).annotate({ expected: 'a string matching the RegExp ^\\S+@\\S+\\.\\S+$' })),
			}),
			Schema.Struct({
				type: Schema.String.annotate({ format: '"phone"' }),
				value: Schema.String.annotate({ format: 'regex' }).check(
					Schema.isPattern(/^\d+$/).annotate({ expected: 'a string matching the RegExp ^\\d+$' })
				),
			}),
		],
		{ mode: 'oneOf' }
	).annotate({ description: 'The identifier (email address or phone number) to send the verification code to.' }),
	templateType: Schema.optionalKey(
		Schema.Union([Schema.String.annotate({ format: '"BindMfa"' }), Schema.String.annotate({ format: '"UserPermissionValidation"' })], {
			mode: 'oneOf',
		}).annotate({
			description:
				'Optional override for the template type used to send the verification code. If the identifier is new, BindNewIdentifier will be used regardless.',
		})
	),
})

export type CreateByVerificationCodeResponse = { readonly verificationRecordId: string; readonly expiresAt: string }
export const CreateByVerificationCodeResponse = Schema.Struct({ verificationRecordId: Schema.String, expiresAt: Schema.String })

export type VerifyByVerificationCodePayload = {
	readonly identifier: { readonly type: string; readonly value: string } | { readonly type: string; readonly value: string }
	readonly verificationId: string
	readonly code: string
}
export const VerifyByVerificationCodePayload = Schema.Struct({
	identifier: Schema.Union(
		[
			Schema.Struct({
				type: Schema.String.annotate({ format: '"email"' }),
				value: Schema.String.annotate({ format: 'regex' })
					.check(Schema.isMaxLength(256).annotate({ expected: 'a value with a length of at most 256' }))
					.check(Schema.isPattern(/^\S+@\S+\.\S+$/).annotate({ expected: 'a string matching the RegExp ^\\S+@\\S+\\.\\S+$' })),
			}),
			Schema.Struct({
				type: Schema.String.annotate({ format: '"phone"' }),
				value: Schema.String.annotate({ format: 'regex' }).check(
					Schema.isPattern(/^\d+$/).annotate({ expected: 'a string matching the RegExp ^\\d+$' })
				),
			}),
		],
		{ mode: 'oneOf' }
	).annotate({
		description:
			'The identifier (email address or phone number) to verify the code against. Must match the identifier used to send the verification code.',
	}),
	verificationId: Schema.String.annotate({ description: 'The verification ID of the CodeVerification record.' }),
	code: Schema.String.annotate({ description: 'The verification code to be verified.' }),
})

export type VerifyByVerificationCodeResponse = { readonly verificationRecordId: string }
export const VerifyByVerificationCodeResponse = Schema.Struct({ verificationRecordId: Schema.String })

export type CreateBySocialPayload = {
	readonly state: string
	readonly redirectUri: string
	readonly scope?: string
	readonly connectorId: string
}
export const CreateBySocialPayload = Schema.Struct({
	state: Schema.String.annotate({
		description: 'A random string generated on the client side to prevent CSRF (Cross-Site Request Forgery) attacks.',
	}),
	redirectUri: Schema.String.annotate({
		description:
			'The URI to navigate back to after the user is authenticated by the connected social identity provider and has granted access to the connector.',
	}),
	scope: Schema.optionalKey(
		Schema.String.annotate({
			description:
				'The custom scopes of the social verification. It can be used to request specific permissions from the social identity provider. If provided, it will override the scope configured in the connector settings.',
		})
	),
	connectorId: Schema.String.annotate({ description: 'The Logto connector ID.' }),
})

export type CreateBySocialResponse = {
	readonly verificationRecordId: string
	readonly authorizationUri: string
	readonly expiresAt: string
}
export const CreateBySocialResponse = Schema.Struct({
	verificationRecordId: Schema.String.annotate({ description: 'The ID of the verification record.' }),
	authorizationUri: Schema.String.annotate({
		description: 'The authorization URI to navigate to for authentication and authorization in the connected social identity provider.',
	}),
	expiresAt: Schema.String.annotate({ description: 'The expiration date and time of the verification record.' }),
})

export type VerifyBySocialPayload = {
	readonly connectorData: { readonly [x: string]: Schema.Json }
	readonly verificationRecordId: string
	readonly verificationId?: Schema.Json
}
export const VerifyBySocialPayload = Schema.Struct({
	connectorData: Schema.Record(Schema.String, Schema.Json.annotate({ expected: 'JSON value' })).annotate({
		description:
			'A json object constructed from the url query params returned by the social platform. Typically it contains `code`, `state` and `redirectUri` fields.',
	}),
	verificationRecordId: Schema.String,
	verificationId: Schema.optionalKey(
		Schema.Json.annotate({ expected: 'JSON value', description: 'The verification ID of the SocialVerification record.' })
	),
})

export type VerifyBySocialResponse = { readonly verificationRecordId: string }
export const VerifyBySocialResponse = Schema.Struct({ verificationRecordId: Schema.String })

export type GenerateWebAuthnRegistrationOptionsResponse = {
	readonly verificationRecordId: string
	readonly registrationOptions: {
		readonly rp: { readonly name: string; readonly id?: string }
		readonly user: { readonly id: string; readonly name: string; readonly displayName: string }
		readonly challenge: string
		readonly pubKeyCredParams: ReadonlyArray<{ readonly type: string; readonly alg: number }>
		readonly timeout?: number
		readonly excludeCredentials?: ReadonlyArray<{
			readonly type: string
			readonly id: string
			readonly transports?: ReadonlyArray<'usb' | 'nfc' | 'ble' | 'internal' | 'cable' | 'hybrid' | 'smart-card'>
		}>
		readonly authenticatorSelection?: {
			readonly authenticatorAttachment?: 'platform' | 'cross-platform'
			readonly requireResidentKey?: boolean
			readonly residentKey?: 'discouraged' | 'preferred' | 'required'
			readonly userVerification?: 'required' | 'preferred' | 'discouraged'
		}
		readonly attestation?: 'none' | 'indirect' | 'direct' | 'enterprise'
		readonly extensions?: { readonly appid?: string; readonly credProps?: boolean; readonly hmacCreateSecret?: boolean }
	}
	readonly expiresAt: string
}
export const GenerateWebAuthnRegistrationOptionsResponse = Schema.Struct({
	verificationRecordId: Schema.String,
	registrationOptions: Schema.Struct({
		rp: Schema.Struct({ name: Schema.String, id: Schema.optionalKey(Schema.String) }),
		user: Schema.Struct({ id: Schema.String, name: Schema.String, displayName: Schema.String }),
		challenge: Schema.String,
		pubKeyCredParams: Schema.Array(
			Schema.Struct({
				type: Schema.String.annotate({ format: '"public-key"' }),
				alg: Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' })),
			})
		),
		timeout: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
		excludeCredentials: Schema.optionalKey(
			Schema.Array(
				Schema.Struct({
					type: Schema.String.annotate({ format: '"public-key"' }),
					id: Schema.String,
					transports: Schema.optionalKey(
						Schema.Array(Schema.Literals(['usb', 'nfc', 'ble', 'internal', 'cable', 'hybrid', 'smart-card']))
					),
				})
			)
		),
		authenticatorSelection: Schema.optionalKey(
			Schema.Struct({
				authenticatorAttachment: Schema.optionalKey(Schema.Literals(['platform', 'cross-platform'])),
				requireResidentKey: Schema.optionalKey(Schema.Boolean),
				residentKey: Schema.optionalKey(Schema.Literals(['discouraged', 'preferred', 'required'])),
				userVerification: Schema.optionalKey(Schema.Literals(['required', 'preferred', 'discouraged'])),
			})
		),
		attestation: Schema.optionalKey(Schema.Literals(['none', 'indirect', 'direct', 'enterprise'])),
		extensions: Schema.optionalKey(
			Schema.Struct({
				appid: Schema.optionalKey(Schema.String),
				credProps: Schema.optionalKey(Schema.Boolean),
				hmacCreateSecret: Schema.optionalKey(Schema.Boolean),
			})
		),
	}),
	expiresAt: Schema.String,
})

export type VerifyWebAuthnRegistrationPayload = {
	readonly verificationRecordId: string
	readonly payload: {
		readonly type: string
		readonly id: string
		readonly rawId: string
		readonly response: {
			readonly clientDataJSON: string
			readonly attestationObject: string
			readonly authenticatorData?: string
			readonly transports?: ReadonlyArray<'usb' | 'nfc' | 'ble' | 'internal' | 'cable' | 'hybrid' | 'smart-card'>
			readonly publicKeyAlgorithm?: number
			readonly publicKey?: string
		}
		readonly authenticatorAttachment?: 'cross-platform' | 'platform'
		readonly clientExtensionResults: {
			readonly appid?: boolean
			readonly crepProps?: { readonly rk?: boolean }
			readonly hmacCreateSecret?: boolean
		}
	}
}
export const VerifyWebAuthnRegistrationPayload = Schema.Struct({
	verificationRecordId: Schema.String.annotate({ description: 'The ID of the verification record.' }),
	payload: Schema.Struct({
		type: Schema.String.annotate({ format: '"WebAuthn"' }),
		id: Schema.String,
		rawId: Schema.String,
		response: Schema.Struct({
			clientDataJSON: Schema.String,
			attestationObject: Schema.String,
			authenticatorData: Schema.optionalKey(Schema.String),
			transports: Schema.optionalKey(
				Schema.Array(Schema.Literals(['usb', 'nfc', 'ble', 'internal', 'cable', 'hybrid', 'smart-card']))
			),
			publicKeyAlgorithm: Schema.optionalKey(Schema.Number.check(Schema.isFinite().annotate({ expected: 'a finite number' }))),
			publicKey: Schema.optionalKey(Schema.String),
		}),
		authenticatorAttachment: Schema.optionalKey(Schema.Literals(['cross-platform', 'platform'])),
		clientExtensionResults: Schema.Struct({
			appid: Schema.optionalKey(Schema.Boolean),
			crepProps: Schema.optionalKey(Schema.Struct({ rk: Schema.optionalKey(Schema.Boolean) })),
			hmacCreateSecret: Schema.optionalKey(Schema.Boolean),
		}),
	}).annotate({ description: 'The payload of the WebAuthn device.' }),
})

export type VerifyWebAuthnRegistrationResponse = { readonly verificationRecordId: string }
export const VerifyWebAuthnRegistrationResponse = Schema.Struct({ verificationRecordId: Schema.String })
