/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as HttpClientRequest from 'effect/unstable/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/unstable/http/HttpClientResponse'

import type { ConnectorFactoriesOperations } from '../../../application/operation/connector-factories.ts'
import { GetResponse, ListResponse } from '../../../domain/schema/connector-factories.ts'
import type { Transport } from '../transport.ts'

export const makeConnectorFactories = ({
	withResponse,
	decodeSuccess,
	unexpectedStatus,
	searchParams,
}: Transport): ConnectorFactoriesOperations => ({
	list: options =>
		HttpClientRequest.get(`/api/connector-factories`).pipe(
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ListResponse), orElse: unexpectedStatus }))
		),
	get: (id, options) =>
		HttpClientRequest.get(`/api/connector-factories/${encodeURIComponent(id)}`).pipe(
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(GetResponse), orElse: unexpectedStatus }))
		),
})
