/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Effect from 'effect/Effect'
import * as HttpClientRequest from 'effect/unstable/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/unstable/http/HttpClientResponse'

import type { ConnectorsOperations } from '../../../application/operation/connectors.ts'
import {
	CreateAuthorizationUriResponse,
	CreateResponse,
	GetResponse,
	ListResponse,
	UpdateResponse,
} from '../../../domain/schema/connectors.ts'
import type { Transport } from '../transport.ts'

export const makeConnectors = ({ withResponse, decodeSuccess, unexpectedStatus, searchParams }: Transport): ConnectorsOperations => ({
	list: options =>
		HttpClientRequest.get(`/api/connectors`).pipe(
			HttpClientRequest.setUrlParams({ target: options?.params?.['target'] as any }),
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ListResponse), orElse: unexpectedStatus }))
		),
	create: options =>
		HttpClientRequest.post(`/api/connectors`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(CreateResponse), orElse: unexpectedStatus }))
		),
	get: (id, options) =>
		HttpClientRequest.get(`/api/connectors/${encodeURIComponent(id)}`).pipe(
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(GetResponse), orElse: unexpectedStatus }))
		),
	delete: (id, options) =>
		HttpClientRequest.delete(`/api/connectors/${encodeURIComponent(id)}`).pipe(
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
		),
	update: (id, options) =>
		HttpClientRequest.patch(`/api/connectors/${encodeURIComponent(id)}`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(UpdateResponse), orElse: unexpectedStatus }))
		),
	createTest: (factoryId, options) =>
		HttpClientRequest.post(`/api/connectors/${encodeURIComponent(factoryId)}/test`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
		),
	createAuthorizationUri: (connectorId, options) =>
		HttpClientRequest.post(`/api/connectors/${encodeURIComponent(connectorId)}/authorization-uri`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(
				HttpClientResponse.matchStatus({ '2xx': decodeSuccess(CreateAuthorizationUriResponse), orElse: unexpectedStatus })
			)
		),
})
