/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Effect from 'effect/Effect'
import * as HttpClientRequest from 'effect/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/http/HttpClientResponse'

import type { ConnectorsOperations } from '../../../application/operation/connectors.ts'
import {
	CreateAuthorizationUriResponse,
	CreateResponse,
	GetResponse,
	ListResponse,
	UpdateResponse,
} from '../../../domain/schema/connectors.ts'
import type { Transport } from '../transport.ts'

export const makeConnectors = ({
	withResponse,
	decodeSuccess,
	unexpectedStatus,
	searchParams,
	__makePathRequest,
	__encodePathParam,
}: Transport): ConnectorsOperations => ({
	list: options =>
		HttpClientRequest.get('/api/connectors').pipe(
			HttpClientRequest.setUrlParams({ target: options?.params?.['target'] as any }),
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ListResponse), orElse: unexpectedStatus }))
		),
	create: options =>
		HttpClientRequest.post('/api/connectors').pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(CreateResponse), orElse: unexpectedStatus }))
		),
	get: (id, options) =>
		__makePathRequest(HttpClientRequest.get, [id], () => '/api/connectors/' + __encodePathParam(id) + '').pipe(
			Effect.flatMap(request =>
				request.pipe(
					withResponse(options?.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(GetResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
	delete: (id, options) =>
		__makePathRequest(HttpClientRequest.delete, [id], () => '/api/connectors/' + __encodePathParam(id) + '').pipe(
			Effect.flatMap(request =>
				request.pipe(
					withResponse(options?.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
				)
			)
		),
	update: (id, options) =>
		__makePathRequest(HttpClientRequest.patch, [id], () => '/api/connectors/' + __encodePathParam(id) + '').pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.bodyJsonUnsafe(options.payload),
					withResponse(options.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(UpdateResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
	createTest: (factoryId, options) =>
		__makePathRequest(HttpClientRequest.post, [factoryId], () => '/api/connectors/' + __encodePathParam(factoryId) + '/test').pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.bodyJsonUnsafe(options.payload),
					withResponse(options.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
				)
			)
		),
	createAuthorizationUri: (connectorId, options) =>
		__makePathRequest(
			HttpClientRequest.post,
			[connectorId],
			() => '/api/connectors/' + __encodePathParam(connectorId) + '/authorization-uri'
		).pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.bodyJsonUnsafe(options.payload),
					withResponse(options.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(CreateAuthorizationUriResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
})
