/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Effect from 'effect/Effect'
import * as HttpClientRequest from 'effect/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/http/HttpClientResponse'

import type { EmailTemplatesOperations } from '../../../application/operation/email-templates.ts'
import {
	DeleteManyResponse,
	GetResponse,
	ListResponse,
	ReplaceResponse,
	UpdateDetailsResponse,
} from '../../../domain/schema/email-templates.ts'
import type { Transport } from '../transport.ts'

export const makeEmailTemplates = ({
	withResponse,
	decodeSuccess,
	unexpectedStatus,
	searchParams,
	__makePathRequest,
	__encodePathParam,
}: Transport): EmailTemplatesOperations => ({
	list: options =>
		HttpClientRequest.get('/api/email-templates').pipe(
			HttpClientRequest.setUrlParams({
				languageTag: options?.params?.['languageTag'] as any,
				templateType: options?.params?.['templateType'] as any,
			}),
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ListResponse), orElse: unexpectedStatus }))
		),
	replace: options =>
		HttpClientRequest.put('/api/email-templates').pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(
				HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ReplaceResponse), orElse: unexpectedStatus })
			)
		),
	deleteMany: options =>
		HttpClientRequest.delete('/api/email-templates').pipe(
			HttpClientRequest.setUrlParams({
				languageTag: options?.params?.['languageTag'] as any,
				templateType: options?.params?.['templateType'] as any,
			}),
			withResponse(options?.config)(
				HttpClientResponse.matchStatus({ '2xx': decodeSuccess(DeleteManyResponse), orElse: unexpectedStatus })
			)
		),
	get: (id, options) =>
		__makePathRequest(HttpClientRequest.get, [id], () => '/api/email-templates/' + __encodePathParam(id) + '').pipe(
			Effect.flatMap(request =>
				request.pipe(
					withResponse(options?.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(GetResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
	delete: (id, options) =>
		__makePathRequest(HttpClientRequest.delete, [id], () => '/api/email-templates/' + __encodePathParam(id) + '').pipe(
			Effect.flatMap(request =>
				request.pipe(
					withResponse(options?.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
				)
			)
		),
	updateDetails: (id, options) =>
		__makePathRequest(HttpClientRequest.patch, [id], () => '/api/email-templates/' + __encodePathParam(id) + '/details').pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.bodyJsonUnsafe(options.payload),
					withResponse(options.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(UpdateDetailsResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
})
