/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Effect from 'effect/Effect'
import * as HttpClientRequest from 'effect/unstable/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/unstable/http/HttpClientResponse'

import type { EmailTemplatesOperations } from '../../../application/operation/email-templates.ts'
import {
	DeleteManyResponse,
	GetResponse,
	ListResponse,
	ReplaceResponse,
	UpdateDetailsResponse,
} from '../../../domain/schema/email-templates.ts'
import type { Transport } from '../transport.ts'

export const makeEmailTemplates = ({
	withResponse,
	decodeSuccess,
	unexpectedStatus,
	searchParams,
}: Transport): EmailTemplatesOperations => ({
	list: options =>
		HttpClientRequest.get(`/api/email-templates`).pipe(
			HttpClientRequest.setUrlParams({
				languageTag: options?.params?.['languageTag'] as any,
				templateType: options?.params?.['templateType'] as any,
			}),
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ListResponse), orElse: unexpectedStatus }))
		),
	replace: options =>
		HttpClientRequest.put(`/api/email-templates`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(
				HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ReplaceResponse), orElse: unexpectedStatus })
			)
		),
	deleteMany: options =>
		HttpClientRequest.delete(`/api/email-templates`).pipe(
			HttpClientRequest.setUrlParams({
				languageTag: options?.params?.['languageTag'] as any,
				templateType: options?.params?.['templateType'] as any,
			}),
			withResponse(options?.config)(
				HttpClientResponse.matchStatus({ '2xx': decodeSuccess(DeleteManyResponse), orElse: unexpectedStatus })
			)
		),
	get: (id, options) =>
		HttpClientRequest.get(`/api/email-templates/${encodeURIComponent(id)}`).pipe(
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(GetResponse), orElse: unexpectedStatus }))
		),
	delete: (id, options) =>
		HttpClientRequest.delete(`/api/email-templates/${encodeURIComponent(id)}`).pipe(
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
		),
	updateDetails: (id, options) =>
		HttpClientRequest.patch(`/api/email-templates/${encodeURIComponent(id)}/details`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(
				HttpClientResponse.matchStatus({ '2xx': decodeSuccess(UpdateDetailsResponse), orElse: unexpectedStatus })
			)
		),
})
