/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import type { LogtoManagementApi, LogtoAccountApi, LogtoExperienceApi, LogtoPublicApi } from '../../../application/operation/index.ts'
import type { Transport } from '../transport.ts'
import { makeAccountCenter } from './account-center.ts'
import { makeApplications } from './applications.ts'
import { makeAuditLogs } from './audit-logs.ts'
import { makeAuthn } from './authn.ts'
import { makeCaptchaProvider } from './captcha-provider.ts'
import { makeCimd } from './cimd.ts'
import { makeConfigs } from './configs.ts'
import { makeConnectorFactories } from './connector-factories.ts'
import { makeConnectors } from './connectors.ts'
import { makeCustomPhrases } from './custom-phrases.ts'
import { makeCustomProfileFields } from './custom-profile-fields.ts'
import { makeDashboard } from './dashboard.ts'
import { makeDomains } from './domains.ts'
import { makeEmailTemplates } from './email-templates.ts'
import { makeExperience } from './experience.ts'
import { makeHooks } from './hooks.ts'
import { makeMyAccount } from './my-account.ts'
import { makeOneTimeTokens } from './one-time-tokens.ts'
import { makeOrganizationInvitations } from './organization-invitations.ts'
import { makeOrganizationRoles } from './organization-roles.ts'
import { makeOrganizations } from './organizations.ts'
import { makeOrganizationScopes } from './organization-scopes.ts'
import { makeResources } from './resources.ts'
import { makeRoles } from './roles.ts'
import { makeSamlApplications } from './saml-applications.ts'
import { makeSamlApplicationsAuthFlow } from './saml-applications-auth-flow.ts'
import { makeSecrets } from './secrets.ts'
import { makeSentinelActivities } from './sentinel-activities.ts'
import { makeSignInExperience } from './sign-in-experience.ts'
import { makeSsoConnectorProviders } from './sso-connector-providers.ts'
import { makeSsoConnectors } from './sso-connectors.ts'
import { makeStatus } from './status.ts'
import { makeSubjectTokens } from './subject-tokens.ts'
import { makeSwagger } from './swagger.ts'
import { makeSystems } from './systems.ts'
import { makeUserAssets } from './user-assets.ts'
import { makeUsers } from './users.ts'
import { makeVerificationCodes } from './verification-codes.ts'
import { makeVerifications } from './verifications.ts'
import { makeWellKnown } from './well-known.ts'

export const makeManagementApi = (transport: Transport): LogtoManagementApi => ({
	accountCenter: makeAccountCenter(transport),
	applications: makeApplications(transport),
	auditLogs: makeAuditLogs(transport),
	captchaProvider: makeCaptchaProvider(transport),
	cimd: makeCimd(transport),
	configs: makeConfigs(transport),
	connectorFactories: makeConnectorFactories(transport),
	connectors: makeConnectors(transport),
	customPhrases: makeCustomPhrases(transport),
	customProfileFields: makeCustomProfileFields(transport),
	dashboard: makeDashboard(transport),
	domains: makeDomains(transport),
	emailTemplates: makeEmailTemplates(transport),
	hooks: makeHooks(transport),
	oneTimeTokens: makeOneTimeTokens(transport),
	organizationInvitations: makeOrganizationInvitations(transport),
	organizationRoles: makeOrganizationRoles(transport),
	organizations: makeOrganizations(transport),
	organizationScopes: makeOrganizationScopes(transport),
	resources: makeResources(transport),
	roles: makeRoles(transport),
	samlApplications: makeSamlApplications(transport),
	secrets: makeSecrets(transport),
	sentinelActivities: makeSentinelActivities(transport),
	signInExperience: makeSignInExperience(transport),
	ssoConnectorProviders: makeSsoConnectorProviders(transport),
	ssoConnectors: makeSsoConnectors(transport),
	subjectTokens: makeSubjectTokens(transport),
	systems: makeSystems(transport),
	userAssets: makeUserAssets(transport),
	users: makeUsers(transport),
	verificationCodes: makeVerificationCodes(transport),
})

export const makeAccountApi = (transport: Transport): LogtoAccountApi => ({
	myAccount: makeMyAccount(transport),
	verifications: makeVerifications(transport),
})

export const makeExperienceApi = (transport: Transport): LogtoExperienceApi => ({ experience: makeExperience(transport) })

export const makePublicApi = (transport: Transport): LogtoPublicApi => ({
	authn: makeAuthn(transport),
	samlApplicationsAuthFlow: makeSamlApplicationsAuthFlow(transport),
	status: makeStatus(transport),
	swagger: makeSwagger(transport),
	wellKnown: makeWellKnown(transport),
})
