/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Effect from 'effect/Effect'
import * as HttpClientRequest from 'effect/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/http/HttpClientResponse'

import type { OrganizationRolesOperations } from '../../../application/operation/organization-roles.ts'
import {
	CreateResponse,
	GetResponse,
	ListResourceScopesResponse,
	ListResponse,
	ListScopesResponse,
	UpdateResponse,
} from '../../../domain/schema/organization-roles.ts'
import type { Transport } from '../transport.ts'

export const makeOrganizationRoles = ({
	withResponse,
	decodeSuccess,
	unexpectedStatus,
	searchParams,
	__makePathRequest,
	__encodePathParam,
}: Transport): OrganizationRolesOperations => ({
	get: (id, options) =>
		__makePathRequest(HttpClientRequest.get, [id], () => '/api/organization-roles/' + __encodePathParam(id) + '').pipe(
			Effect.flatMap(request =>
				request.pipe(
					withResponse(options?.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(GetResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
	delete: (id, options) =>
		__makePathRequest(HttpClientRequest.delete, [id], () => '/api/organization-roles/' + __encodePathParam(id) + '').pipe(
			Effect.flatMap(request =>
				request.pipe(
					withResponse(options?.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
				)
			)
		),
	update: (id, options) =>
		__makePathRequest(HttpClientRequest.patch, [id], () => '/api/organization-roles/' + __encodePathParam(id) + '').pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.bodyJsonUnsafe(options.payload),
					withResponse(options.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(UpdateResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
	list: options =>
		HttpClientRequest.get('/api/organization-roles').pipe(
			HttpClientRequest.setUrlParams({
				q: options?.params?.['q'] as any,
				page: options?.params?.['page'] as any,
				page_size: options?.params?.['page_size'] as any,
			}),
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ListResponse), orElse: unexpectedStatus }))
		),
	create: options =>
		HttpClientRequest.post('/api/organization-roles').pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(CreateResponse), orElse: unexpectedStatus }))
		),
	listScopes: (id, options) =>
		__makePathRequest(HttpClientRequest.get, [id], () => '/api/organization-roles/' + __encodePathParam(id) + '/scopes').pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.setUrlParams({
						page: options?.params?.['page'] as any,
						page_size: options?.params?.['page_size'] as any,
					}),
					withResponse(options?.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ListScopesResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
	replaceScopes: (id, options) =>
		__makePathRequest(HttpClientRequest.put, [id], () => '/api/organization-roles/' + __encodePathParam(id) + '/scopes').pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.bodyJsonUnsafe(options.payload),
					withResponse(options.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
				)
			)
		),
	createScope: (id, options) =>
		__makePathRequest(HttpClientRequest.post, [id], () => '/api/organization-roles/' + __encodePathParam(id) + '/scopes').pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.bodyJsonUnsafe(options.payload),
					withResponse(options.config)(HttpClientResponse.matchStatus({ orElse: unexpectedStatus }))
				)
			)
		),
	deleteScope: (id, organizationScopeId, options) =>
		__makePathRequest(
			HttpClientRequest.delete,
			[id, organizationScopeId],
			() => '/api/organization-roles/' + __encodePathParam(id) + '/scopes/' + __encodePathParam(organizationScopeId) + ''
		).pipe(
			Effect.flatMap(request =>
				request.pipe(
					withResponse(options?.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
				)
			)
		),
	listResourceScopes: (id, options) =>
		__makePathRequest(HttpClientRequest.get, [id], () => '/api/organization-roles/' + __encodePathParam(id) + '/resource-scopes').pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.setUrlParams({
						page: options?.params?.['page'] as any,
						page_size: options?.params?.['page_size'] as any,
					}),
					withResponse(options?.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ListResourceScopesResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
	replaceResourceScopes: (id, options) =>
		__makePathRequest(HttpClientRequest.put, [id], () => '/api/organization-roles/' + __encodePathParam(id) + '/resource-scopes').pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.bodyJsonUnsafe(options.payload),
					withResponse(options.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
				)
			)
		),
	createResourceScope: (id, options) =>
		__makePathRequest(HttpClientRequest.post, [id], () => '/api/organization-roles/' + __encodePathParam(id) + '/resource-scopes').pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.bodyJsonUnsafe(options.payload),
					withResponse(options.config)(HttpClientResponse.matchStatus({ orElse: unexpectedStatus }))
				)
			)
		),
	deleteResourceScope: (id, scopeId, options) =>
		__makePathRequest(
			HttpClientRequest.delete,
			[id, scopeId],
			() => '/api/organization-roles/' + __encodePathParam(id) + '/resource-scopes/' + __encodePathParam(scopeId) + ''
		).pipe(
			Effect.flatMap(request =>
				request.pipe(
					withResponse(options?.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
				)
			)
		),
})
