/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Effect from 'effect/Effect'
import * as HttpClientRequest from 'effect/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/http/HttpClientResponse'

import type { SecretsOperations } from '../../../application/operation/secrets.ts'
import type { Transport } from '../transport.ts'

export const makeSecrets = ({
	withResponse,
	decodeSuccess,
	unexpectedStatus,
	searchParams,
	__makePathRequest,
	__encodePathParam,
}: Transport): SecretsOperations => ({
	delete: (id, options) =>
		__makePathRequest(HttpClientRequest.delete, [id], () => '/api/secrets/' + __encodePathParam(id) + '').pipe(
			Effect.flatMap(request =>
				request.pipe(
					withResponse(options?.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
				)
			)
		),
})
