/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Effect from 'effect/Effect'
import * as HttpClientRequest from 'effect/unstable/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/unstable/http/HttpClientResponse'

import type { SentinelActivitiesOperations } from '../../../application/operation/sentinel-activities.ts'
import type { Transport } from '../transport.ts'

export const makeSentinelActivities = ({
	withResponse,
	decodeSuccess,
	unexpectedStatus,
	searchParams,
}: Transport): SentinelActivitiesOperations => ({
	delete: options =>
		HttpClientRequest.post(`/api/sentinel-activities/delete`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
		),
})
