/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as HttpClientRequest from 'effect/unstable/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/unstable/http/HttpClientResponse'

import type { SsoConnectorProvidersOperations } from '../../../application/operation/sso-connector-providers.ts'
import { ListResponse } from '../../../domain/schema/sso-connector-providers.ts'
import type { Transport } from '../transport.ts'

export const makeSsoConnectorProviders = ({
	withResponse,
	decodeSuccess,
	unexpectedStatus,
	searchParams,
}: Transport): SsoConnectorProvidersOperations => ({
	list: options =>
		HttpClientRequest.get(`/api/sso-connector-providers`).pipe(
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ListResponse), orElse: unexpectedStatus }))
		),
})
