/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Effect from 'effect/Effect'
import * as HttpClientRequest from 'effect/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/http/HttpClientResponse'

import type { SsoConnectorsOperations } from '../../../application/operation/sso-connectors.ts'
import {
	CreateResponse,
	CreateSigningKeyResponse,
	GetResponse,
	ListResponse,
	ListSigningKeysResponse,
	UpdateResponse,
	UpdateSigningKeyResponse,
} from '../../../domain/schema/sso-connectors.ts'
import type { Transport } from '../transport.ts'

export const makeSsoConnectors = ({
	withResponse,
	decodeSuccess,
	unexpectedStatus,
	searchParams,
	__makePathRequest,
	__encodePathParam,
}: Transport): SsoConnectorsOperations => ({
	list: options =>
		HttpClientRequest.get('/api/sso-connectors').pipe(
			HttpClientRequest.setUrlParams({ page: options?.params?.['page'] as any, page_size: options?.params?.['page_size'] as any }),
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ListResponse), orElse: unexpectedStatus }))
		),
	create: options =>
		HttpClientRequest.post('/api/sso-connectors').pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(CreateResponse), orElse: unexpectedStatus }))
		),
	get: (id, options) =>
		__makePathRequest(HttpClientRequest.get, [id], () => '/api/sso-connectors/' + __encodePathParam(id) + '').pipe(
			Effect.flatMap(request =>
				request.pipe(
					withResponse(options?.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(GetResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
	delete: (id, options) =>
		__makePathRequest(HttpClientRequest.delete, [id], () => '/api/sso-connectors/' + __encodePathParam(id) + '').pipe(
			Effect.flatMap(request =>
				request.pipe(
					withResponse(options?.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
				)
			)
		),
	update: (id, options) =>
		__makePathRequest(HttpClientRequest.patch, [id], () => '/api/sso-connectors/' + __encodePathParam(id) + '').pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.bodyJsonUnsafe(options.payload),
					withResponse(options.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(UpdateResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
	listSigningKeys: (id, options) =>
		__makePathRequest(HttpClientRequest.get, [id], () => '/api/sso-connectors/' + __encodePathParam(id) + '/signing-keys').pipe(
			Effect.flatMap(request =>
				request.pipe(
					withResponse(options?.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ListSigningKeysResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
	createSigningKey: (id, options) =>
		__makePathRequest(HttpClientRequest.post, [id], () => '/api/sso-connectors/' + __encodePathParam(id) + '/signing-keys').pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.bodyJsonUnsafe(options.payload),
					withResponse(options.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(CreateSigningKeyResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
	deleteSigningKey: (id, keyId, options) =>
		__makePathRequest(
			HttpClientRequest.delete,
			[id, keyId],
			() => '/api/sso-connectors/' + __encodePathParam(id) + '/signing-keys/' + __encodePathParam(keyId) + ''
		).pipe(
			Effect.flatMap(request =>
				request.pipe(
					withResponse(options?.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
				)
			)
		),
	updateSigningKey: (id, keyId, options) =>
		__makePathRequest(
			HttpClientRequest.patch,
			[id, keyId],
			() => '/api/sso-connectors/' + __encodePathParam(id) + '/signing-keys/' + __encodePathParam(keyId) + ''
		).pipe(
			Effect.flatMap(request =>
				request.pipe(
					HttpClientRequest.bodyJsonUnsafe(options.payload),
					withResponse(options.config)(
						HttpClientResponse.matchStatus({ '2xx': decodeSuccess(UpdateSigningKeyResponse), orElse: unexpectedStatus })
					)
				)
			)
		),
})
