/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Effect from 'effect/Effect'
import * as HttpClientRequest from 'effect/unstable/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/unstable/http/HttpClientResponse'

import type { SsoConnectorsOperations } from '../../../application/operation/sso-connectors.ts'
import {
	CreateResponse,
	CreateSigningKeyResponse,
	GetResponse,
	ListResponse,
	ListSigningKeysResponse,
	UpdateResponse,
	UpdateSigningKeyResponse,
} from '../../../domain/schema/sso-connectors.ts'
import type { Transport } from '../transport.ts'

export const makeSsoConnectors = ({ withResponse, decodeSuccess, unexpectedStatus, searchParams }: Transport): SsoConnectorsOperations => ({
	list: options =>
		HttpClientRequest.get(`/api/sso-connectors`).pipe(
			HttpClientRequest.setUrlParams({ page: options?.params?.['page'] as any, page_size: options?.params?.['page_size'] as any }),
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ListResponse), orElse: unexpectedStatus }))
		),
	create: options =>
		HttpClientRequest.post(`/api/sso-connectors`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(CreateResponse), orElse: unexpectedStatus }))
		),
	get: (id, options) =>
		HttpClientRequest.get(`/api/sso-connectors/${encodeURIComponent(id)}`).pipe(
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(GetResponse), orElse: unexpectedStatus }))
		),
	delete: (id, options) =>
		HttpClientRequest.delete(`/api/sso-connectors/${encodeURIComponent(id)}`).pipe(
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
		),
	update: (id, options) =>
		HttpClientRequest.patch(`/api/sso-connectors/${encodeURIComponent(id)}`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(UpdateResponse), orElse: unexpectedStatus }))
		),
	listSigningKeys: (id, options) =>
		HttpClientRequest.get(`/api/sso-connectors/${encodeURIComponent(id)}/signing-keys`).pipe(
			withResponse(options?.config)(
				HttpClientResponse.matchStatus({ '2xx': decodeSuccess(ListSigningKeysResponse), orElse: unexpectedStatus })
			)
		),
	createSigningKey: (id, options) =>
		HttpClientRequest.post(`/api/sso-connectors/${encodeURIComponent(id)}/signing-keys`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(
				HttpClientResponse.matchStatus({ '2xx': decodeSuccess(CreateSigningKeyResponse), orElse: unexpectedStatus })
			)
		),
	deleteSigningKey: (id, keyId, options) =>
		HttpClientRequest.delete(`/api/sso-connectors/${encodeURIComponent(id)}/signing-keys/${encodeURIComponent(keyId)}`).pipe(
			withResponse(options?.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
		),
	updateSigningKey: (id, keyId, options) =>
		HttpClientRequest.patch(`/api/sso-connectors/${encodeURIComponent(id)}/signing-keys/${encodeURIComponent(keyId)}`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(
				HttpClientResponse.matchStatus({ '2xx': decodeSuccess(UpdateSigningKeyResponse), orElse: unexpectedStatus })
			)
		),
})
