/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as HttpClientRequest from 'effect/unstable/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/unstable/http/HttpClientResponse'

import type { SubjectTokensOperations } from '../../../application/operation/subject-tokens.ts'
import { CreateResponse } from '../../../domain/schema/subject-tokens.ts'
import type { Transport } from '../transport.ts'

export const makeSubjectTokens = ({ withResponse, decodeSuccess, unexpectedStatus, searchParams }: Transport): SubjectTokensOperations => ({
	create: options =>
		HttpClientRequest.post(`/api/subject-tokens`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(HttpClientResponse.matchStatus({ '2xx': decodeSuccess(CreateResponse), orElse: unexpectedStatus }))
		),
})
