/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as HttpClientRequest from 'effect/unstable/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/unstable/http/HttpClientResponse'

import type { SwaggerOperations } from '../../../application/operation/swagger.ts'
import type { Transport } from '../transport.ts'

export const makeSwagger = ({ withResponse, decodeSuccess, unexpectedStatus, searchParams }: Transport): SwaggerOperations => ({
	get: options =>
		HttpClientRequest.get(`/api/swagger.json`).pipe(
			withResponse(options?.config)(HttpClientResponse.matchStatus({ orElse: unexpectedStatus }))
		),
})
