/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as HttpClientRequest from 'effect/unstable/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/unstable/http/HttpClientResponse'

import type { SystemsOperations } from '../../../application/operation/systems.ts'
import { GetApplicationConfigResponse } from '../../../domain/schema/systems.ts'
import type { Transport } from '../transport.ts'

export const makeSystems = ({ withResponse, decodeSuccess, unexpectedStatus, searchParams }: Transport): SystemsOperations => ({
	getApplicationConfig: options =>
		HttpClientRequest.get(`/api/systems/application`).pipe(
			withResponse(options?.config)(
				HttpClientResponse.matchStatus({ '2xx': decodeSuccess(GetApplicationConfigResponse), orElse: unexpectedStatus })
			)
		),
})
