/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import * as Effect from 'effect/Effect'
import * as HttpClientRequest from 'effect/unstable/http/HttpClientRequest'
import * as HttpClientResponse from 'effect/unstable/http/HttpClientResponse'

import type { VerificationCodesOperations } from '../../../application/operation/verification-codes.ts'
import type { Transport } from '../transport.ts'

export const makeVerificationCodes = ({
	withResponse,
	decodeSuccess,
	unexpectedStatus,
	searchParams,
}: Transport): VerificationCodesOperations => ({
	create: options =>
		HttpClientRequest.post(`/api/verification-codes`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
		),
	verify: options =>
		HttpClientRequest.post(`/api/verification-codes/verify`).pipe(
			HttpClientRequest.bodyJsonUnsafe(options.payload),
			withResponse(options.config)(HttpClientResponse.matchStatus({ '204': () => Effect.void, orElse: unexpectedStatus }))
		),
})
