/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import type * as Effect from 'effect/Effect'

import type { LogtoError, OperationConfig, WithOptionalResponse } from '../config.ts'
import type {
	AssignRolesPayload,
	AssignRolesResponse,
	CreatePayload,
	CreateProtectedAppMetadataCustomDomainPayload,
	CreateResponse,
	CreateSecretPayload,
	CreateSecretResponse,
	CreateUserConsentOrganizationPayload,
	CreateUserConsentScopePayload,
	DeleteLegacySecretResponse,
	GetAccessControlResponse,
	GetResponse,
	GetSignInExperienceResponse,
	ListOrganizationsParams,
	ListOrganizationsResponse,
	ListParams,
	ListProtectedAppMetadataCustomDomainsResponse,
	ListResponse,
	ListRolesParams,
	ListRolesResponse,
	ListSecretsResponse,
	ListUserConsentOrganizationsParams,
	ListUserConsentOrganizationsResponse,
	ListUserConsentScopesResponse,
	ReplaceAccessControlPayload,
	ReplaceAccessControlResponse,
	ReplaceRolesPayload,
	ReplaceSignInExperiencePayload,
	ReplaceSignInExperienceResponse200,
	ReplaceSignInExperienceResponse201,
	ReplaceUserConsentOrganizationsPayload,
	UpdateCustomDataPayload,
	UpdateCustomDataResponse,
	UpdatePayload,
	UpdateResponse,
	UpdateSecretPayload,
	UpdateSecretResponse,
} from '../../domain/schema/applications.ts'

/**
 * Logto `Applications` endpoints.
 */
export interface ApplicationsOperations {
	/**
	 * Get applications that match the given query with pagination.
	 */
	readonly list: <Config extends OperationConfig>(
		options: { readonly params?: ListParams | undefined; readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListResponse, Config>, LogtoError>
	/**
	 * Create a new application with the given data.
	 */
	readonly create: <Config extends OperationConfig>(options: {
		readonly payload: CreatePayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<CreateResponse, Config>, LogtoError>
	/**
	 * Get application details by ID.
	 */
	readonly get: <Config extends OperationConfig>(
		id: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetResponse, Config>, LogtoError>
	/**
	 * Delete application by ID.
	 */
	readonly delete: <Config extends OperationConfig>(
		id: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Update application details by ID with the given data.
	 */
	readonly update: <Config extends OperationConfig>(
		id: string,
		options: { readonly payload: UpdatePayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<UpdateResponse, Config>, LogtoError>
	/**
	 * Update the custom data of an application.
	 */
	readonly updateCustomData: <Config extends OperationConfig>(
		applicationId: string,
		options: { readonly payload: UpdateCustomDataPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<UpdateCustomDataResponse, Config>, LogtoError>
	/**
	 * Get the app-level access-control rule configuration for the specified application.
	 */
	readonly getAccessControl: <Config extends OperationConfig>(
		applicationId: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetAccessControlResponse, Config>, LogtoError>
	/**
	 * Replace the app-level access-control rule configuration for the specified application.
	 */
	readonly replaceAccessControl: <Config extends OperationConfig>(
		applicationId: string,
		options: { readonly payload: ReplaceAccessControlPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<ReplaceAccessControlResponse, Config>, LogtoError>
	/**
	 * Get API resource roles assigned to the specified application with pagination.
	 */
	readonly listRoles: <Config extends OperationConfig>(
		applicationId: string,
		options: { readonly params?: ListRolesParams | undefined; readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListRolesResponse, Config>, LogtoError>
	/**
	 * Update API resource roles assigned to the specified application. This will replace the existing API resource roles.
	 */
	readonly replaceRoles: <Config extends OperationConfig>(
		applicationId: string,
		options: { readonly payload: ReplaceRolesPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Assign API resource roles to the specified application. The API resource roles will be added to the existing API resource roles. Role IDs that are already assigned to the application are silently ignored.
	 */
	readonly assignRoles: <Config extends OperationConfig>(
		applicationId: string,
		options: { readonly payload: AssignRolesPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<AssignRolesResponse, Config>, LogtoError>
	/**
	 * Remove a API resource role from the specified application.
	 */
	readonly deleteRole: <Config extends OperationConfig>(
		applicationId: string,
		roleId: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Get custom domains of the specified application, the application type should be protected app.
	 */
	readonly listProtectedAppMetadataCustomDomains: <Config extends OperationConfig>(
		id: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListProtectedAppMetadataCustomDomainsResponse, Config>, LogtoError>
	/**
	 * Add a custom domain to the application. You'll need to setup DNS record later.
	 */
	readonly createProtectedAppMetadataCustomDomain: <Config extends OperationConfig>(
		id: string,
		options: { readonly payload: CreateProtectedAppMetadataCustomDomainPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Remove custom domain from the specified application.
	 */
	readonly deleteProtectedAppMetadataCustomDomain: <Config extends OperationConfig>(
		id: string,
		domain: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Get the list of organizations that an application is associated with.
	 */
	readonly listOrganizations: <Config extends OperationConfig>(
		id: string,
		options: { readonly params?: ListOrganizationsParams | undefined; readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListOrganizationsResponse, Config>, LogtoError>
	/**
	 * Delete the legacy secret for the application and replace it with an internal secret used only by Logto. The internal secret is not returned by Management APIs and cannot be used for client authentication.
	 */
	readonly deleteLegacySecret: <Config extends OperationConfig>(
		id: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<DeleteLegacySecretResponse, Config>, LogtoError>
	/**
	 * Get all the secrets for the application.
	 */
	readonly listSecrets: <Config extends OperationConfig>(
		id: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListSecretsResponse, Config>, LogtoError>
	/**
	 * Add a new secret for the application.
	 */
	readonly createSecret: <Config extends OperationConfig>(
		id: string,
		options: { readonly payload: CreateSecretPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<CreateSecretResponse, Config>, LogtoError>
	/**
	 * Delete a secret for the application by name.
	 */
	readonly deleteSecret: <Config extends OperationConfig>(
		id: string,
		name: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Update a secret for the application by name.
	 */
	readonly updateSecret: <Config extends OperationConfig>(
		id: string,
		name: string,
		options: { readonly payload: UpdateSecretPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<UpdateSecretResponse | void, Config>, LogtoError>
	/**
	 * List all the user consent scopes of an application by application id
	 */
	readonly listUserConsentScopes: <Config extends OperationConfig>(
		applicationId: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListUserConsentScopesResponse, Config>, LogtoError>
	/**
	 * Assign the user consent scopes to an application by application id
	 */
	readonly createUserConsentScope: <Config extends OperationConfig>(
		applicationId: string,
		options: { readonly payload: CreateUserConsentScopePayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Remove the user consent scope from an application by application id, scope type and scope id
	 */
	readonly deleteUserConsentScope: <Config extends OperationConfig>(
		applicationId: string,
		scopeType: string,
		scopeId: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Get application level sign-in experience for a given application.
	 *  - Only branding properties and terms links customization is supported for now.
	 *
	 *  - Only third-party applications can have the sign-in experience customization for now.
	 */
	readonly getSignInExperience: <Config extends OperationConfig>(
		applicationId: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetSignInExperienceResponse, Config>, LogtoError>
	/**
	 * Update application level sign-in experience for the specified application. Create a new sign-in experience if it does not exist.
	 *  - Only branding properties and terms links customization is supported for now.
	 *
	 *  - Only third-party applications can be customized for now.
	 *
	 *  - Application level sign-in experience customization is optional, if provided, it will override the default branding and terms links.
	 */
	readonly replaceSignInExperience: <Config extends OperationConfig>(
		applicationId: string,
		options: { readonly payload: ReplaceSignInExperiencePayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<ReplaceSignInExperienceResponse200 | ReplaceSignInExperienceResponse201, Config>, LogtoError>
	/**
	 * List all the user consented organizations for a application by application id and user id.
	 */
	readonly listUserConsentOrganizations: <Config extends OperationConfig>(
		id: string,
		userId: string,
		options: { readonly params?: ListUserConsentOrganizationsParams | undefined; readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListUserConsentOrganizationsResponse, Config>, LogtoError>
	/**
	 * Grant a list of organization access of a user for a application by application id and user id. <br/> The user must be a member of all the organizations. <br/> Only third-party application needs to be granted access to organizations, all the other applications can request for all the organizations' access by default.
	 */
	readonly replaceUserConsentOrganizations: <Config extends OperationConfig>(
		id: string,
		userId: string,
		options: { readonly payload: ReplaceUserConsentOrganizationsPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Grant a list of organization access of a user for a application by application id and user id. <br/> The user must be a member of all the organizations. <br/> Only third-party application needs to be granted access to organizations, all the other applications can request for all the organizations' access by default.
	 */
	readonly createUserConsentOrganization: <Config extends OperationConfig>(
		id: string,
		userId: string,
		options: { readonly payload: CreateUserConsentOrganizationPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Revoke a user's access to an organization for a application by application id, user id and organization id.
	 */
	readonly deleteUserConsentOrganization: <Config extends OperationConfig>(
		id: string,
		userId: string,
		organizationId: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
}
