/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import type * as Effect from 'effect/Effect'

import type { LogtoError, OperationConfig, WithOptionalResponse } from '../config.ts'
import type {
	AssertSamlPayload,
	AssertSingleSignOnSamlPayload,
	GetHasuraAuthParams,
	GetHasuraAuthResponse,
} from '../../domain/schema/authn.ts'

/**
 * Logto `Authn` endpoints.
 */
export interface AuthnOperations {
	/**
	 * The `HASURA_GRAPHQL_AUTH_HOOK` endpoint for Hasura auth. Use this endpoint to integrate Hasura's [webhook authentication flow](https://hasura.io/docs/latest/auth/authentication/webhook/).
	 */
	readonly getHasuraAuth: <Config extends OperationConfig>(options: {
		readonly params: GetHasuraAuthParams
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<GetHasuraAuthResponse, Config>, LogtoError>
	/**
	 * The Assertion Consumer Service (ACS) endpoint for Simple Assertion Markup Language (SAML) social connectors.
	 *
	 * SAML social connectors are deprecated. Use the SSO SAML connector instead.
	 */
	readonly assertSaml: <Config extends OperationConfig>(
		connectorId: string,
		options: { readonly payload: AssertSamlPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * The Assertion Consumer Service (ACS) endpoint for Simple Assertion Markup Language (SAML) single sign-on (SSO) connectors.
	 *
	 * This endpoint is used to complete the SAML SSO authentication flow. It receives the SAML assertion response from the identity provider (IdP) and redirects the user to complete the authentication flow.
	 */
	readonly assertSingleSignOnSaml: <Config extends OperationConfig>(
		connectorId: string,
		options: { readonly payload: AssertSingleSignOnSamlPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
}
