/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import type * as Effect from 'effect/Effect'

import type { LogtoError, OperationConfig, WithOptionalResponse } from '../config.ts'
import type { GetResponse, UpdatePayload, UpdateResponse } from '../../domain/schema/captcha-provider.ts'

/**
 * Logto `Captcha provider` endpoints.
 */
export interface CaptchaProviderOperations {
	/**
	 * Get the captcha provider, you can only have one captcha provider.
	 */
	readonly get: <Config extends OperationConfig>(
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetResponse, Config>, LogtoError>
	/**
	 * Update the captcha provider with the provided settings.
	 */
	readonly update: <Config extends OperationConfig>(options: {
		readonly payload: UpdatePayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<UpdateResponse, Config>, LogtoError>
	/**
	 * Delete the captcha provider.
	 */
	readonly delete: <Config extends OperationConfig>(
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
}
