/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import type * as Effect from 'effect/Effect'

import type { LogtoError, OperationConfig, WithOptionalResponse } from '../config.ts'
import type { AssignUserConsentScopesPayload, ListUserConsentScopesResponse } from '../../domain/schema/cimd.ts'

/**
 * Logto `CIMD` endpoints.
 */
export interface CimdOperations {
	/**
	 * List the tenant-level permission ceiling for CIMD clients: user scopes, API resource scopes, organization scopes, and organization API resource scopes.
	 */
	readonly listUserConsentScopes: <Config extends OperationConfig>(
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListUserConsentScopesResponse, Config>, LogtoError>
	/**
	 * Add scopes to the tenant-level permission ceiling for CIMD clients. Database-backed scopes are referenced by ID; Management API scopes can never be selected.
	 */
	readonly assignUserConsentScopes: <Config extends OperationConfig>(options: {
		readonly payload: AssignUserConsentScopesPayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Remove a scope from the tenant-level permission ceiling for CIMD clients.
	 */
	readonly deleteUserConsentScope: <Config extends OperationConfig>(
		scopeType: string,
		scopeId: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
}
