/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import type * as Effect from 'effect/Effect'

import type { LogtoError, OperationConfig, WithOptionalResponse } from '../config.ts'
import type {
	GetActionResponse,
	GetAdminConsoleConfigResponse,
	GetCimdConfigResponse,
	GetIdTokenConfigResponse,
	GetJwtCustomizerResponse,
	GetOidcKeysResponse,
	GetOidcSessionConfigResponse,
	ListActionsResponse,
	ListJwtCustomizersResponse,
	RotateOidcKeysPayload,
	RotateOidcKeysResponse,
	TestActionPayload,
	TestActionResponse,
	TestJwtCustomizerPayload,
	TestJwtCustomizerResponse,
	UpdateActionPayload,
	UpdateActionResponse,
	UpdateAdminConsoleConfigPayload,
	UpdateAdminConsoleConfigResponse,
	UpdateCimdConfigPayload,
	UpdateCimdConfigResponse,
	UpdateJwtCustomizerPayload,
	UpdateJwtCustomizerResponse,
	UpdateOidcSessionConfigPayload,
	UpdateOidcSessionConfigResponse,
	UpsertActionPayload,
	UpsertActionResponse200,
	UpsertActionResponse201,
	UpsertIdTokenConfigPayload,
	UpsertIdTokenConfigResponse,
	UpsertJwtCustomizerPayload,
	UpsertJwtCustomizerResponse200,
	UpsertJwtCustomizerResponse201,
} from '../../domain/schema/configs.ts'

/**
 * Logto `Configs` endpoints.
 */
export interface ConfigsOperations {
	/**
	 * Get the global configuration object for Logto Console.
	 */
	readonly getAdminConsoleConfig: <Config extends OperationConfig>(
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetAdminConsoleConfigResponse, Config>, LogtoError>
	/**
	 * Update the global configuration object for Logto Console. This method performs a partial update.
	 */
	readonly updateAdminConsoleConfig: <Config extends OperationConfig>(options: {
		readonly payload: UpdateAdminConsoleConfigPayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<UpdateAdminConsoleConfigResponse, Config>, LogtoError>
	/**
	 * Get the OIDC session configuration for the tenant.
	 */
	readonly getOidcSessionConfig: <Config extends OperationConfig>(
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetOidcSessionConfigResponse, Config>, LogtoError>
	/**
	 * Update the OIDC session configuration for the tenant. This method performs a partial update. If the configuration does not exist, it will be created.
	 */
	readonly updateOidcSessionConfig: <Config extends OperationConfig>(options: {
		readonly payload: UpdateOidcSessionConfigPayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<UpdateOidcSessionConfigResponse, Config>, LogtoError>
	/**
	 * Get OIDC signing keys by key type. The actual key will be redacted from the result.
	 */
	readonly getOidcKeys: <Config extends OperationConfig>(
		keyType: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetOidcKeysResponse, Config>, LogtoError>
	/**
	 * Delete an OIDC signing key by key type and key ID.
	 */
	readonly deleteOidcKey: <Config extends OperationConfig>(
		keyType: string,
		keyId: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * A new key will be generated and prepend to the list of keys.
	 *
	 * Only two recent keys will be kept. The oldest key will be automatically removed if there are more than two keys.
	 */
	readonly rotateOidcKeys: <Config extends OperationConfig>(
		keyType: string,
		options: { readonly payload: RotateOidcKeysPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<RotateOidcKeysResponse, Config>, LogtoError>
	/**
	 * Get the JWT customizer for the given token type.
	 */
	readonly getJwtCustomizer: <Config extends OperationConfig>(
		tokenTypePath: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetJwtCustomizerResponse, Config>, LogtoError>
	/**
	 * Create or update a JWT customizer for the given token type.
	 */
	readonly upsertJwtCustomizer: <Config extends OperationConfig>(
		tokenTypePath: string,
		options: { readonly payload: UpsertJwtCustomizerPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<UpsertJwtCustomizerResponse200 | UpsertJwtCustomizerResponse201, Config>, LogtoError>
	/**
	 * Delete the JWT customizer for the given token type.
	 */
	readonly deleteJwtCustomizer: <Config extends OperationConfig>(
		tokenTypePath: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Update the JWT customizer for the given token type.
	 */
	readonly updateJwtCustomizer: <Config extends OperationConfig>(
		tokenTypePath: string,
		options: { readonly payload: UpdateJwtCustomizerPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<UpdateJwtCustomizerResponse, Config>, LogtoError>
	/**
	 * Get all JWT customizers for the tenant.
	 */
	readonly listJwtCustomizers: <Config extends OperationConfig>(
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListJwtCustomizersResponse, Config>, LogtoError>
	/**
	 * Test the JWT customizer script with the given sample context and sample token payload.
	 */
	readonly testJwtCustomizer: <Config extends OperationConfig>(options: {
		readonly payload: TestJwtCustomizerPayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<TestJwtCustomizerResponse, Config>, LogtoError>
	/**
	 * Get the ID token extended claims configuration for the tenant. This configuration controls which extended claims (e.g., `custom_data`, `identities`, `roles`, `organizations`, `organization_roles`) are included in ID tokens.
	 */
	readonly getIdTokenConfig: <Config extends OperationConfig>(
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetIdTokenConfigResponse, Config>, LogtoError>
	/**
	 * Create or update the ID token extended claims configuration for the tenant. This controls which extended claims are included in ID tokens when the corresponding scopes are requested.
	 */
	readonly upsertIdTokenConfig: <Config extends OperationConfig>(options: {
		readonly payload: UpsertIdTokenConfigPayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<UpsertIdTokenConfigResponse, Config>, LogtoError>
	/**
	 * Get all action configurations for the tenant.
	 */
	readonly listActions: <Config extends OperationConfig>(
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListActionsResponse, Config>, LogtoError>
	/**
	 * Test an action script with a sample context.
	 */
	readonly testAction: <Config extends OperationConfig>(options: {
		readonly payload: TestActionPayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<TestActionResponse | void, Config>, LogtoError>
	/**
	 * Get the action configuration for the given action type.
	 */
	readonly getAction: <Config extends OperationConfig>(
		actionType: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetActionResponse, Config>, LogtoError>
	/**
	 * Create or update an action configuration for the given action type.
	 */
	readonly upsertAction: <Config extends OperationConfig>(
		actionType: string,
		options: { readonly payload: UpsertActionPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<UpsertActionResponse200 | UpsertActionResponse201, Config>, LogtoError>
	/**
	 * Delete the action configuration for the given action type.
	 */
	readonly deleteAction: <Config extends OperationConfig>(
		actionType: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Update the action configuration for the given action type.
	 */
	readonly updateAction: <Config extends OperationConfig>(
		actionType: string,
		options: { readonly payload: UpdateActionPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<UpdateActionResponse, Config>, LogtoError>
	/**
	 * Get the tenant-level OAuth Client ID Metadata Document (CIMD) configuration. A missing configuration resolves to the disabled state.
	 */
	readonly getCimdConfig: <Config extends OperationConfig>(
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetCimdConfigResponse, Config>, LogtoError>
	/**
	 * Update the tenant-level OAuth Client ID Metadata Document (CIMD) switch. Enabling requires the OIDC provider SSRF protection to be active.
	 */
	readonly updateCimdConfig: <Config extends OperationConfig>(options: {
		readonly payload: UpdateCimdConfigPayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<UpdateCimdConfigResponse, Config>, LogtoError>
}
