/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import type * as Effect from 'effect/Effect'

import type { LogtoError, OperationConfig, WithOptionalResponse } from '../config.ts'
import type {
	CreateAuthorizationUriPayload,
	CreateAuthorizationUriResponse,
	CreatePayload,
	CreateResponse,
	CreateTestPayload,
	GetResponse,
	ListParams,
	ListResponse,
	UpdatePayload,
	UpdateResponse,
} from '../../domain/schema/connectors.ts'

/**
 * Logto `Connectors` endpoints.
 */
export interface ConnectorsOperations {
	/**
	 * Get all connectors in the current tenant.
	 */
	readonly list: <Config extends OperationConfig>(
		options: { readonly params?: ListParams | undefined; readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListResponse, Config>, LogtoError>
	/**
	 * Create a connector with the given data.
	 */
	readonly create: <Config extends OperationConfig>(options: {
		readonly payload: CreatePayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<CreateResponse, Config>, LogtoError>
	/**
	 * Get connector data by ID
	 */
	readonly get: <Config extends OperationConfig>(
		id: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetResponse, Config>, LogtoError>
	/**
	 * Delete connector by ID.
	 */
	readonly delete: <Config extends OperationConfig>(
		id: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Update connector by ID with the given data. This methods performs a partial update.
	 */
	readonly update: <Config extends OperationConfig>(
		id: string,
		options: { readonly payload: UpdatePayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<UpdateResponse, Config>, LogtoError>
	/**
	 * Test a passwordless (email or SMS) connector by sending a test message to the given phone number or email address.
	 */
	readonly createTest: <Config extends OperationConfig>(
		factoryId: string,
		options: { readonly payload: CreateTestPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Get authorization URI for specified connector by providing redirect URI and randomly generated state.
	 */
	readonly createAuthorizationUri: <Config extends OperationConfig>(
		connectorId: string,
		options: { readonly payload: CreateAuthorizationUriPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<CreateAuthorizationUriResponse, Config>, LogtoError>
}
