/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import type * as Effect from 'effect/Effect'

import type { LogtoError, OperationConfig, WithOptionalResponse } from '../config.ts'
import type { GetResponse, ListResponse, ReplacePayload, ReplaceResponse } from '../../domain/schema/custom-phrases.ts'

/**
 * Logto `Custom phrases` endpoints.
 */
export interface CustomPhrasesOperations {
	/**
	 * Get all custom phrases for all languages.
	 */
	readonly list: <Config extends OperationConfig>(
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListResponse, Config>, LogtoError>
	/**
	 * Get custom phrases for the specified language tag.
	 */
	readonly get: <Config extends OperationConfig>(
		languageTag: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetResponse, Config>, LogtoError>
	/**
	 * Upsert custom phrases for the specified language tag. Upsert means that if the custom phrases already exist, they will be updated. Otherwise, they will be created.
	 */
	readonly replace: <Config extends OperationConfig>(
		languageTag: string,
		options: { readonly payload: ReplacePayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<ReplaceResponse, Config>, LogtoError>
	/**
	 * Delete custom phrases for the specified language tag.
	 */
	readonly delete: <Config extends OperationConfig>(
		languageTag: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
}
