/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import type * as Effect from 'effect/Effect'

import type { LogtoError, OperationConfig, WithOptionalResponse } from '../config.ts'
import type {
	CreateMessagePayload,
	CreatePayload,
	CreateResponse,
	GetResponse,
	ListParams,
	ListResponse,
	ReplaceStatusPayload,
	ReplaceStatusResponse,
} from '../../domain/schema/organization-invitations.ts'

/**
 * Logto `Organization invitations` endpoints.
 */
export interface OrganizationInvitationsOperations {
	/**
	 * Get an organization invitation by ID.
	 */
	readonly get: <Config extends OperationConfig>(
		id: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetResponse, Config>, LogtoError>
	/**
	 * Delete an organization invitation by ID.
	 */
	readonly delete: <Config extends OperationConfig>(
		id: string,
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Get organization invitations.
	 */
	readonly list: <Config extends OperationConfig>(
		options: { readonly params?: ListParams | undefined; readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListResponse, Config>, LogtoError>
	/**
	 * Create an organization invitation and optionally send it via email. The tenant should have an email connector configured if you want to send the invitation via email at this point.
	 */
	readonly create: <Config extends OperationConfig>(options: {
		readonly payload: CreatePayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<CreateResponse, Config>, LogtoError>
	/**
	 * Resend the invitation message to the invitee.
	 */
	readonly createMessage: <Config extends OperationConfig>(
		id: string,
		options: { readonly payload: CreateMessagePayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<void, Config>, LogtoError>
	/**
	 * Update the status of an organization invitation by ID.
	 */
	readonly replaceStatus: <Config extends OperationConfig>(
		id: string,
		options: { readonly payload: ReplaceStatusPayload; readonly config?: Config | undefined }
	) => Effect.Effect<WithOptionalResponse<ReplaceStatusResponse, Config>, LogtoError>
}
