/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import type * as Effect from 'effect/Effect'

import type { LogtoError, OperationConfig, WithOptionalResponse } from '../config.ts'
import type {
	CheckPasswordWithDefaultSignInExperiencePayload,
	CheckPasswordWithDefaultSignInExperienceResponse,
	GetResponse,
	GetUsernameCaseSensitivityConflictsParams,
	GetUsernameCaseSensitivityConflictsResponse,
	UpdateParams,
	UpdatePayload,
	UpdateResponse,
	UploadCustomUiAssetsFormData,
	UploadCustomUiAssetsResponse,
} from '../../domain/schema/sign-in-experience.ts'

/**
 * Logto `Sign-in experience` endpoints.
 */
export interface SignInExperienceOperations {
	/**
	 * Get the default sign-in experience settings.
	 */
	readonly get: <Config extends OperationConfig>(
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GetResponse, Config>, LogtoError>
	/**
	 * Update the default sign-in experience settings with the provided data.
	 */
	readonly update: <Config extends OperationConfig>(options: {
		readonly params?: UpdateParams | undefined
		readonly payload: UpdatePayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<UpdateResponse, Config>, LogtoError>
	/**
	 * Check if a password meets the password policy in the sign-in experience settings.
	 */
	readonly checkPasswordWithDefaultSignInExperience: <Config extends OperationConfig>(options: {
		readonly payload: CheckPasswordWithDefaultSignInExperiencePayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<CheckPasswordWithDefaultSignInExperienceResponse, Config>, LogtoError>
	/**
	 * Upload a zip file containing custom web assets such as HTML, CSS, and JavaScript files, then replace the default sign-in experience with the custom UI assets.
	 */
	readonly uploadCustomUiAssets: <Config extends OperationConfig>(options: {
		readonly payload: UploadCustomUiAssetsFormData
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<UploadCustomUiAssetsResponse, Config>, LogtoError>
	/**
	 * List groups of usernames that collide when compared case-insensitively (i.e. usernames that would clash if the tenant switched to a case-insensitive username policy), with the total group count and a capped sample. Useful for surfacing conflicts before disabling case sensitivity.
	 */
	readonly getUsernameCaseSensitivityConflicts: <Config extends OperationConfig>(options: {
		readonly params: GetUsernameCaseSensitivityConflictsParams
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<GetUsernameCaseSensitivityConflictsResponse, Config>, LogtoError>
}
