/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import type * as Effect from 'effect/Effect'

import type { LogtoError, OperationConfig, WithOptionalResponse } from '../config.ts'
import type { ListResponse } from '../../domain/schema/sso-connector-providers.ts'

/**
 * Logto `SSO connector providers` endpoints.
 */
export interface SsoConnectorProvidersOperations {
	/**
	 * Get a complete list of supported SSO connector providers.
	 */
	readonly list: <Config extends OperationConfig>(
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<ListResponse, Config>, LogtoError>
}
