/**
 * Generated by scripts/generate.ts from spec/openapi.json — do not edit by hand.
 */
import type * as Effect from 'effect/Effect'

import type { LogtoError, OperationConfig, WithOptionalResponse } from '../config.ts'
import type {
	CreateByPasswordPayload,
	CreateByPasswordResponse,
	CreateBySocialPayload,
	CreateBySocialResponse,
	CreateByVerificationCodePayload,
	CreateByVerificationCodeResponse,
	GenerateWebAuthnRegistrationOptionsResponse,
	VerifyBySocialPayload,
	VerifyBySocialResponse,
	VerifyByVerificationCodePayload,
	VerifyByVerificationCodeResponse,
	VerifyWebAuthnRegistrationPayload,
	VerifyWebAuthnRegistrationResponse,
} from '../../domain/schema/verifications.ts'

/**
 * Logto `Verifications` endpoints.
 */
export interface VerificationsOperations {
	/**
	 * Create a verification record by verifying the password.
	 */
	readonly createByPassword: <Config extends OperationConfig>(options: {
		readonly payload: CreateByPasswordPayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<CreateByPasswordResponse, Config>, LogtoError>
	/**
	 * Create a verification record and send the code to the specified identifier. The code verification can be used to verify the given identifier.
	 */
	readonly createByVerificationCode: <Config extends OperationConfig>(options: {
		readonly payload: CreateByVerificationCodePayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<CreateByVerificationCodeResponse, Config>, LogtoError>
	/**
	 * Verify the provided verification code against the identifier. If successful, the verification record will be marked as verified.
	 */
	readonly verifyByVerificationCode: <Config extends OperationConfig>(options: {
		readonly payload: VerifyByVerificationCodePayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<VerifyByVerificationCodeResponse, Config>, LogtoError>
	/**
	 * Create a social verification record and return the authorization URI.
	 */
	readonly createBySocial: <Config extends OperationConfig>(options: {
		readonly payload: CreateBySocialPayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<CreateBySocialResponse, Config>, LogtoError>
	/**
	 * Verify a social verification record by callback connector data, and save the user information to the record.
	 */
	readonly verifyBySocial: <Config extends OperationConfig>(options: {
		readonly payload: VerifyBySocialPayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<VerifyBySocialResponse, Config>, LogtoError>
	/**
	 * Generate WebAuthn registration options for the user to register a new WebAuthn device.
	 */
	readonly generateWebAuthnRegistrationOptions: <Config extends OperationConfig>(
		options: { readonly config?: Config | undefined } | undefined
	) => Effect.Effect<WithOptionalResponse<GenerateWebAuthnRegistrationOptionsResponse, Config>, LogtoError>
	/**
	 * Verify the WebAuthn registration by the user's response.
	 */
	readonly verifyWebAuthnRegistration: <Config extends OperationConfig>(options: {
		readonly payload: VerifyWebAuthnRegistrationPayload
		readonly config?: Config | undefined
	}) => Effect.Effect<WithOptionalResponse<VerifyWebAuthnRegistrationResponse, Config>, LogtoError>
}
